// Code generated by ent, DO NOT EDIT.

package userfederatedidentity

import (
	"entgo.io/ent/dialect/sql"
	"sanzi.io/muid/internal/authn/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEQ(FieldUserID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEQ(FieldProvider, v))
}

// ProviderUserID applies equality check predicate on the "provider_user_id" field. It's identical to ProviderUserIDEQ.
func ProviderUserID(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEQ(FieldProviderUserID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldContainsFold(FieldUserID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderUserIDEQ applies the EQ predicate on the "provider_user_id" field.
func ProviderUserIDEQ(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEQ(FieldProviderUserID, v))
}

// ProviderUserIDNEQ applies the NEQ predicate on the "provider_user_id" field.
func ProviderUserIDNEQ(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldNEQ(FieldProviderUserID, v))
}

// ProviderUserIDIn applies the In predicate on the "provider_user_id" field.
func ProviderUserIDIn(vs ...string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldIn(FieldProviderUserID, vs...))
}

// ProviderUserIDNotIn applies the NotIn predicate on the "provider_user_id" field.
func ProviderUserIDNotIn(vs ...string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldNotIn(FieldProviderUserID, vs...))
}

// ProviderUserIDGT applies the GT predicate on the "provider_user_id" field.
func ProviderUserIDGT(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldGT(FieldProviderUserID, v))
}

// ProviderUserIDGTE applies the GTE predicate on the "provider_user_id" field.
func ProviderUserIDGTE(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldGTE(FieldProviderUserID, v))
}

// ProviderUserIDLT applies the LT predicate on the "provider_user_id" field.
func ProviderUserIDLT(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldLT(FieldProviderUserID, v))
}

// ProviderUserIDLTE applies the LTE predicate on the "provider_user_id" field.
func ProviderUserIDLTE(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldLTE(FieldProviderUserID, v))
}

// ProviderUserIDContains applies the Contains predicate on the "provider_user_id" field.
func ProviderUserIDContains(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldContains(FieldProviderUserID, v))
}

// ProviderUserIDHasPrefix applies the HasPrefix predicate on the "provider_user_id" field.
func ProviderUserIDHasPrefix(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldHasPrefix(FieldProviderUserID, v))
}

// ProviderUserIDHasSuffix applies the HasSuffix predicate on the "provider_user_id" field.
func ProviderUserIDHasSuffix(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldHasSuffix(FieldProviderUserID, v))
}

// ProviderUserIDEqualFold applies the EqualFold predicate on the "provider_user_id" field.
func ProviderUserIDEqualFold(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldEqualFold(FieldProviderUserID, v))
}

// ProviderUserIDContainsFold applies the ContainsFold predicate on the "provider_user_id" field.
func ProviderUserIDContainsFold(v string) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.FieldContainsFold(FieldProviderUserID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserFederatedIdentity) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserFederatedIdentity) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserFederatedIdentity) predicate.UserFederatedIdentity {
	return predicate.UserFederatedIdentity(sql.NotPredicates(p))
}
