// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// OrganizationMember is the predicate function for organizationmember builders.
type OrganizationMember func(*sql.Selector)

// OrganizationRole is the predicate function for organizationrole builders.
type OrganizationRole func(*sql.Selector)

// RolePermission is the predicate function for rolepermission builders.
type RolePermission func(*sql.Selector)

// UserRef is the predicate function for userref builders.
type UserRef func(*sql.Selector)
