// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateway/v1/services.proto

package gatewayv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_gateway_v1_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetMeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetMeRequest_builder) Build() *GetMeRequest {
	m0 := &GetMeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetMeResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *User                  `protobuf:"bytes,1,opt,name=user,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_gateway_v1_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetMeResponse) GetUser() *User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *GetMeResponse) SetUser(v *User) {
	x.xxx_hidden_User = v
}

func (x *GetMeResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *GetMeResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type GetMeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *User
}

func (b0 GetMeResponse_builder) Build() *GetMeResponse {
	m0 := &GetMeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

// User mirrors the public-facing subset of a profile.
type User struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Username    string                 `protobuf:"bytes,2,opt,name=username,proto3"`
	xxx_hidden_DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3"`
	xxx_hidden_Email       string                 `protobuf:"bytes,4,opt,name=email,proto3"`
	xxx_hidden_AvatarUrl   string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gateway_v1_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.xxx_hidden_Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.xxx_hidden_DisplayName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.xxx_hidden_AvatarUrl
	}
	return ""
}

func (x *User) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *User) SetUsername(v string) {
	x.xxx_hidden_Username = v
}

func (x *User) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = v
}

func (x *User) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *User) SetAvatarUrl(v string) {
	x.xxx_hidden_AvatarUrl = v
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          string
	Username    string
	DisplayName string
	Email       string
	AvatarUrl   string
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Username = b.Username
	x.xxx_hidden_DisplayName = b.DisplayName
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_AvatarUrl = b.AvatarUrl
	return m0
}

var File_gateway_v1_services_proto protoreflect.FileDescriptor

const file_gateway_v1_services_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/v1/services.proto\x12\x0fmuid.gateway.v1\x1a\x1bbuf/validate/validate.proto\"\x0e\n" +
	"\fGetMeRequest\":\n" +
	"\rGetMeResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.muid.gateway.v1.UserR\x04user\"\x94\x01\n" +
	"\x04User\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl2`\n" +
	"\x16ServicesGatewayService\x12F\n" +
	"\x05GetMe\x12\x1d.muid.gateway.v1.GetMeRequest\x1a\x1e.muid.gateway.v1.GetMeResponseB\xb0\x01\n" +
	"\x13com.muid.gateway.v1B\rServicesProtoP\x01Z,sanzi.io/muid/api/proto/gateway/v1;gatewayv1\xa2\x02\x03MGX\xaa\x02\x0fMuid.Gateway.V1\xca\x02\x0fMuid\\Gateway\\V1\xe2\x02\x1bMuid\\Gateway\\V1\\GPBMetadata\xea\x02\x11Muid::Gateway::V1b\x06proto3"

var file_gateway_v1_services_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_v1_services_proto_goTypes = []any{
	(*GetMeRequest)(nil),  // 0: muid.gateway.v1.GetMeRequest
	(*GetMeResponse)(nil), // 1: muid.gateway.v1.GetMeResponse
	(*User)(nil),          // 2: muid.gateway.v1.User
}
var file_gateway_v1_services_proto_depIdxs = []int32{
	2, // 0: muid.gateway.v1.GetMeResponse.user:type_name -> muid.gateway.v1.User
	0, // 1: muid.gateway.v1.ServicesGatewayService.GetMe:input_type -> muid.gateway.v1.GetMeRequest
	1, // 2: muid.gateway.v1.ServicesGatewayService.GetMe:output_type -> muid.gateway.v1.GetMeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_v1_services_proto_init() }
func file_gateway_v1_services_proto_init() {
	if File_gateway_v1_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_services_proto_rawDesc), len(file_gateway_v1_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_services_proto_goTypes,
		DependencyIndexes: file_gateway_v1_services_proto_depIdxs,
		MessageInfos:      file_gateway_v1_services_proto_msgTypes,
	}.Build()
	File_gateway_v1_services_proto = out.File
	file_gateway_v1_services_proto_goTypes = nil
	file_gateway_v1_services_proto_depIdxs = nil
}
