// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"sanzi.io/muid/internal/profile/ent/organizationprofile"
	"sanzi.io/muid/internal/profile/ent/predicate"
)

// OrganizationProfileUpdate is the builder for updating OrganizationProfile entities.
type OrganizationProfileUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationProfileMutation
}

// Where appends a list predicates to the OrganizationProfileUpdate builder.
func (_u *OrganizationProfileUpdate) Where(ps ...predicate.OrganizationProfile) *OrganizationProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *OrganizationProfileUpdate) SetSlug(v string) *OrganizationProfileUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *OrganizationProfileUpdate) SetNillableSlug(v *string) *OrganizationProfileUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *OrganizationProfileUpdate) SetDisplayName(v string) *OrganizationProfileUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *OrganizationProfileUpdate) SetNillableDisplayName(v *string) *OrganizationProfileUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OrganizationProfileUpdate) SetDescription(v string) *OrganizationProfileUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OrganizationProfileUpdate) SetNillableDescription(v *string) *OrganizationProfileUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationProfileUpdate) SetUpdatedAt(v time.Time) *OrganizationProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OrganizationProfileMutation object of the builder.
func (_u *OrganizationProfileUpdate) Mutation() *OrganizationProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrganizationProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrganizationProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organizationprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationProfileUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := organizationprofile.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "OrganizationProfile.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := organizationprofile.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "OrganizationProfile.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := organizationprofile.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "OrganizationProfile.description": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationprofile.Table, organizationprofile.Columns, sqlgraph.NewFieldSpec(organizationprofile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(organizationprofile.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(organizationprofile.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(organizationprofile.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrganizationProfileUpdateOne is the builder for updating a single OrganizationProfile entity.
type OrganizationProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationProfileMutation
}

// SetSlug sets the "slug" field.
func (_u *OrganizationProfileUpdateOne) SetSlug(v string) *OrganizationProfileUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *OrganizationProfileUpdateOne) SetNillableSlug(v *string) *OrganizationProfileUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *OrganizationProfileUpdateOne) SetDisplayName(v string) *OrganizationProfileUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *OrganizationProfileUpdateOne) SetNillableDisplayName(v *string) *OrganizationProfileUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OrganizationProfileUpdateOne) SetDescription(v string) *OrganizationProfileUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OrganizationProfileUpdateOne) SetNillableDescription(v *string) *OrganizationProfileUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationProfileUpdateOne) SetUpdatedAt(v time.Time) *OrganizationProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OrganizationProfileMutation object of the builder.
func (_u *OrganizationProfileUpdateOne) Mutation() *OrganizationProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrganizationProfileUpdate builder.
func (_u *OrganizationProfileUpdateOne) Where(ps ...predicate.OrganizationProfile) *OrganizationProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrganizationProfileUpdateOne) Select(field string, fields ...string) *OrganizationProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrganizationProfile entity.
func (_u *OrganizationProfileUpdateOne) Save(ctx context.Context) (*OrganizationProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationProfileUpdateOne) SaveX(ctx context.Context) *OrganizationProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrganizationProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organizationprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := organizationprofile.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "OrganizationProfile.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := organizationprofile.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "OrganizationProfile.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := organizationprofile.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "OrganizationProfile.description": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationProfileUpdateOne) sqlSave(ctx context.Context) (_node *OrganizationProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationprofile.Table, organizationprofile.Columns, sqlgraph.NewFieldSpec(organizationprofile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrganizationProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationprofile.FieldID)
		for _, f := range fields {
			if !organizationprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organizationprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(organizationprofile.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(organizationprofile.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(organizationprofile.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OrganizationProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
