// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"sanzi.io/muid/internal/profile/ent/predicate"
	"sanzi.io/muid/internal/profile/ent/useravatar"
	"sanzi.io/muid/internal/profile/ent/userprofile"
)

// UserAvatarUpdate is the builder for updating UserAvatar entities.
type UserAvatarUpdate struct {
	config
	hooks    []Hook
	mutation *UserAvatarMutation
}

// Where appends a list predicates to the UserAvatarUpdate builder.
func (_u *UserAvatarUpdate) Where(ps ...predicate.UserAvatar) *UserAvatarUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAvatarUpdate) SetUserID(v uuid.UUID) *UserAvatarUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAvatarUpdate) SetNillableUserID(v *uuid.UUID) *UserAvatarUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *UserAvatarUpdate) SetObjectKey(v string) *UserAvatarUpdate {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *UserAvatarUpdate) SetNillableObjectKey(v *string) *UserAvatarUpdate {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *UserAvatarUpdate) SetContentType(v string) *UserAvatarUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *UserAvatarUpdate) SetNillableContentType(v *string) *UserAvatarUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *UserAvatarUpdate) SetByteSize(v int64) *UserAvatarUpdate {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *UserAvatarUpdate) SetNillableByteSize(v *int64) *UserAvatarUpdate {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *UserAvatarUpdate) AddByteSize(v int64) *UserAvatarUpdate {
	_u.mutation.AddByteSize(v)
	return _u
}

// SetUploadedAt sets the "uploaded_at" field.
func (_u *UserAvatarUpdate) SetUploadedAt(v time.Time) *UserAvatarUpdate {
	_u.mutation.SetUploadedAt(v)
	return _u
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (_u *UserAvatarUpdate) SetNillableUploadedAt(v *time.Time) *UserAvatarUpdate {
	if v != nil {
		_u.SetUploadedAt(*v)
	}
	return _u
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (_u *UserAvatarUpdate) ClearUploadedAt() *UserAvatarUpdate {
	_u.mutation.ClearUploadedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAvatarUpdate) SetUpdatedAt(v time.Time) *UserAvatarUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the UserProfile entity.
func (_u *UserAvatarUpdate) SetUser(v *UserProfile) *UserAvatarUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserAvatarMutation object of the builder.
func (_u *UserAvatarUpdate) Mutation() *UserAvatarMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the UserProfile entity.
func (_u *UserAvatarUpdate) ClearUser() *UserAvatarUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAvatarUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAvatarUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAvatarUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAvatarUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAvatarUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useravatar.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAvatarUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAvatar.user"`)
	}
	return nil
}

func (_u *UserAvatarUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useravatar.Table, useravatar.Columns, sqlgraph.NewFieldSpec(useravatar.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(useravatar.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(useravatar.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(useravatar.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(useravatar.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UploadedAt(); ok {
		_spec.SetField(useravatar.FieldUploadedAt, field.TypeTime, value)
	}
	if _u.mutation.UploadedAtCleared() {
		_spec.ClearField(useravatar.FieldUploadedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useravatar.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useravatar.UserTable,
			Columns: []string{useravatar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useravatar.UserTable,
			Columns: []string{useravatar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useravatar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAvatarUpdateOne is the builder for updating a single UserAvatar entity.
type UserAvatarUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAvatarMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserAvatarUpdateOne) SetUserID(v uuid.UUID) *UserAvatarUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAvatarUpdateOne) SetNillableUserID(v *uuid.UUID) *UserAvatarUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *UserAvatarUpdateOne) SetObjectKey(v string) *UserAvatarUpdateOne {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *UserAvatarUpdateOne) SetNillableObjectKey(v *string) *UserAvatarUpdateOne {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *UserAvatarUpdateOne) SetContentType(v string) *UserAvatarUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *UserAvatarUpdateOne) SetNillableContentType(v *string) *UserAvatarUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *UserAvatarUpdateOne) SetByteSize(v int64) *UserAvatarUpdateOne {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *UserAvatarUpdateOne) SetNillableByteSize(v *int64) *UserAvatarUpdateOne {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *UserAvatarUpdateOne) AddByteSize(v int64) *UserAvatarUpdateOne {
	_u.mutation.AddByteSize(v)
	return _u
}

// SetUploadedAt sets the "uploaded_at" field.
func (_u *UserAvatarUpdateOne) SetUploadedAt(v time.Time) *UserAvatarUpdateOne {
	_u.mutation.SetUploadedAt(v)
	return _u
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (_u *UserAvatarUpdateOne) SetNillableUploadedAt(v *time.Time) *UserAvatarUpdateOne {
	if v != nil {
		_u.SetUploadedAt(*v)
	}
	return _u
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (_u *UserAvatarUpdateOne) ClearUploadedAt() *UserAvatarUpdateOne {
	_u.mutation.ClearUploadedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAvatarUpdateOne) SetUpdatedAt(v time.Time) *UserAvatarUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the UserProfile entity.
func (_u *UserAvatarUpdateOne) SetUser(v *UserProfile) *UserAvatarUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserAvatarMutation object of the builder.
func (_u *UserAvatarUpdateOne) Mutation() *UserAvatarMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the UserProfile entity.
func (_u *UserAvatarUpdateOne) ClearUser() *UserAvatarUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserAvatarUpdate builder.
func (_u *UserAvatarUpdateOne) Where(ps ...predicate.UserAvatar) *UserAvatarUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAvatarUpdateOne) Select(field string, fields ...string) *UserAvatarUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAvatar entity.
func (_u *UserAvatarUpdateOne) Save(ctx context.Context) (*UserAvatar, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAvatarUpdateOne) SaveX(ctx context.Context) *UserAvatar {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAvatarUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAvatarUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAvatarUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useravatar.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAvatarUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAvatar.user"`)
	}
	return nil
}

func (_u *UserAvatarUpdateOne) sqlSave(ctx context.Context) (_node *UserAvatar, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useravatar.Table, useravatar.Columns, sqlgraph.NewFieldSpec(useravatar.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAvatar.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useravatar.FieldID)
		for _, f := range fields {
			if !useravatar.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useravatar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(useravatar.FieldObjectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(useravatar.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(useravatar.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(useravatar.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UploadedAt(); ok {
		_spec.SetField(useravatar.FieldUploadedAt, field.TypeTime, value)
	}
	if _u.mutation.UploadedAtCleared() {
		_spec.ClearField(useravatar.FieldUploadedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useravatar.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useravatar.UserTable,
			Columns: []string{useravatar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useravatar.UserTable,
			Columns: []string{useravatar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserAvatar{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useravatar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
