// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"sanzi.io/muid/internal/profile/ent/useroriginalidentity"
	"sanzi.io/muid/internal/profile/ent/userprofile"
)

// UserOriginalIdentityCreate is the builder for creating a UserOriginalIdentity entity.
type UserOriginalIdentityCreate struct {
	config
	mutation *UserOriginalIdentityMutation
	hooks    []Hook
}

// SetOriginalIdentity sets the "original_identity" field.
func (_c *UserOriginalIdentityCreate) SetOriginalIdentity(v string) *UserOriginalIdentityCreate {
	_c.mutation.SetOriginalIdentity(v)
	return _c
}

// SetUserID sets the "user" edge to the UserProfile entity by ID.
func (_c *UserOriginalIdentityCreate) SetUserID(id uuid.UUID) *UserOriginalIdentityCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the UserProfile entity.
func (_c *UserOriginalIdentityCreate) SetUser(v *UserProfile) *UserOriginalIdentityCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserOriginalIdentityMutation object of the builder.
func (_c *UserOriginalIdentityCreate) Mutation() *UserOriginalIdentityMutation {
	return _c.mutation
}

// Save creates the UserOriginalIdentity in the database.
func (_c *UserOriginalIdentityCreate) Save(ctx context.Context) (*UserOriginalIdentity, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserOriginalIdentityCreate) SaveX(ctx context.Context) *UserOriginalIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserOriginalIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserOriginalIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserOriginalIdentityCreate) check() error {
	if _, ok := _c.mutation.OriginalIdentity(); !ok {
		return &ValidationError{Name: "original_identity", err: errors.New(`ent: missing required field "UserOriginalIdentity.original_identity"`)}
	}
	if v, ok := _c.mutation.OriginalIdentity(); ok {
		if err := useroriginalidentity.OriginalIdentityValidator(v); err != nil {
			return &ValidationError{Name: "original_identity", err: fmt.Errorf(`ent: validator failed for field "UserOriginalIdentity.original_identity": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserOriginalIdentity.user"`)}
	}
	return nil
}

func (_c *UserOriginalIdentityCreate) sqlSave(ctx context.Context) (*UserOriginalIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserOriginalIdentityCreate) createSpec() (*UserOriginalIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &UserOriginalIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useroriginalidentity.Table, sqlgraph.NewFieldSpec(useroriginalidentity.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.OriginalIdentity(); ok {
		_spec.SetField(useroriginalidentity.FieldOriginalIdentity, field.TypeString, value)
		_node.OriginalIdentity = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useroriginalidentity.UserTable,
			Columns: []string{useroriginalidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_original_identity_user = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserOriginalIdentityCreateBulk is the builder for creating many UserOriginalIdentity entities in bulk.
type UserOriginalIdentityCreateBulk struct {
	config
	err      error
	builders []*UserOriginalIdentityCreate
}

// Save creates the UserOriginalIdentity entities in the database.
func (_c *UserOriginalIdentityCreateBulk) Save(ctx context.Context) ([]*UserOriginalIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserOriginalIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserOriginalIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserOriginalIdentityCreateBulk) SaveX(ctx context.Context) []*UserOriginalIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserOriginalIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserOriginalIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
