// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"sanzi.io/muid/internal/profile/ent/predicate"
	"sanzi.io/muid/internal/profile/ent/useroriginalidentity"
)

// UserOriginalIdentityDelete is the builder for deleting a UserOriginalIdentity entity.
type UserOriginalIdentityDelete struct {
	config
	hooks    []Hook
	mutation *UserOriginalIdentityMutation
}

// Where appends a list predicates to the UserOriginalIdentityDelete builder.
func (_d *UserOriginalIdentityDelete) Where(ps ...predicate.UserOriginalIdentity) *UserOriginalIdentityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserOriginalIdentityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserOriginalIdentityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserOriginalIdentityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(useroriginalidentity.Table, sqlgraph.NewFieldSpec(useroriginalidentity.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserOriginalIdentityDeleteOne is the builder for deleting a single UserOriginalIdentity entity.
type UserOriginalIdentityDeleteOne struct {
	_d *UserOriginalIdentityDelete
}

// Where appends a list predicates to the UserOriginalIdentityDelete builder.
func (_d *UserOriginalIdentityDeleteOne) Where(ps ...predicate.UserOriginalIdentity) *UserOriginalIdentityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserOriginalIdentityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useroriginalidentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserOriginalIdentityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
