// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// UserEmail is the predicate function for useremail builders.
type UserEmail func(*sql.Selector)

// UserFederatedIdentity is the predicate function for userfederatedidentity builders.
type UserFederatedIdentity func(*sql.Selector)

// UserIdentity is the predicate function for useridentity builders.
type UserIdentity func(*sql.Selector)

// UserPasskey is the predicate function for userpasskey builders.
type UserPasskey func(*sql.Selector)

// UserRef is the predicate function for userref builders.
type UserRef func(*sql.Selector)

// UserSession is the predicate function for usersession builders.
type UserSession func(*sql.Selector)
