// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: profile/v1/profile.proto

package profile

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	claims "sanzi.io/muid/api/proto/shared/v1/claims"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProfileRequest struct {
	state               protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Email    string                      `protobuf:"bytes,1,opt,name=email,proto3"`
	xxx_hidden_Identity *claims.IdentityInformation `protobuf:"bytes,2,opt,name=identity,proto3,oneof"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateProfileRequest) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *CreateProfileRequest) GetIdentity() *claims.IdentityInformation {
	if x != nil {
		return x.xxx_hidden_Identity
	}
	return nil
}

func (x *CreateProfileRequest) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *CreateProfileRequest) SetIdentity(v *claims.IdentityInformation) {
	x.xxx_hidden_Identity = v
}

func (x *CreateProfileRequest) HasIdentity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Identity != nil
}

func (x *CreateProfileRequest) ClearIdentity() {
	x.xxx_hidden_Identity = nil
}

type CreateProfileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email string
	// Optional OIDC-style claims: display name is taken from claims when resolvable, otherwise random; username is always auto-allocated (never from email); picture triggers async avatar bootstrap when https.
	Identity *claims.IdentityInformation
}

func (b0 CreateProfileRequest_builder) Build() *CreateProfileRequest {
	m0 := &CreateProfileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Identity = b.Identity
	return m0
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateProfileResponse) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *CreateProfileResponse) SetId(v string) {
	x.xxx_hidden_Id = v
}

type CreateProfileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 CreateProfileResponse_builder) Build() *CreateProfileResponse {
	m0 := &CreateProfileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetProfileRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *GetProfileRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type GetProfileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 GetProfileRequest_builder) Build() *GetProfileRequest {
	m0 := &GetProfileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type GetProfileResponse struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id              string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Email           string                 `protobuf:"bytes,2,opt,name=email,proto3"`
	xxx_hidden_DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3"`
	xxx_hidden_Username        string                 `protobuf:"bytes,4,opt,name=username,proto3"`
	xxx_hidden_AvatarUrl       string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3"`
	xxx_hidden_Locale          string                 `protobuf:"bytes,6,opt,name=locale,proto3"`
	xxx_hidden_AvatarObjectKey string                 `protobuf:"bytes,7,opt,name=avatar_object_key,json=avatarObjectKey,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetProfileResponse) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *GetProfileResponse) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *GetProfileResponse) GetDisplayName() string {
	if x != nil {
		return x.xxx_hidden_DisplayName
	}
	return ""
}

func (x *GetProfileResponse) GetUsername() string {
	if x != nil {
		return x.xxx_hidden_Username
	}
	return ""
}

func (x *GetProfileResponse) GetAvatarUrl() string {
	if x != nil {
		return x.xxx_hidden_AvatarUrl
	}
	return ""
}

func (x *GetProfileResponse) GetLocale() string {
	if x != nil {
		return x.xxx_hidden_Locale
	}
	return ""
}

func (x *GetProfileResponse) GetAvatarObjectKey() string {
	if x != nil {
		return x.xxx_hidden_AvatarObjectKey
	}
	return ""
}

func (x *GetProfileResponse) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *GetProfileResponse) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *GetProfileResponse) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = v
}

func (x *GetProfileResponse) SetUsername(v string) {
	x.xxx_hidden_Username = v
}

func (x *GetProfileResponse) SetAvatarUrl(v string) {
	x.xxx_hidden_AvatarUrl = v
}

func (x *GetProfileResponse) SetLocale(v string) {
	x.xxx_hidden_Locale = v
}

func (x *GetProfileResponse) SetAvatarObjectKey(v string) {
	x.xxx_hidden_AvatarObjectKey = v
}

type GetProfileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id              string
	Email           string
	DisplayName     string
	Username        string
	AvatarUrl       string
	Locale          string
	AvatarObjectKey string
}

func (b0 GetProfileResponse_builder) Build() *GetProfileResponse {
	m0 := &GetProfileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_DisplayName = b.DisplayName
	x.xxx_hidden_Username = b.Username
	x.xxx_hidden_AvatarUrl = b.AvatarUrl
	x.xxx_hidden_Locale = b.Locale
	x.xxx_hidden_AvatarObjectKey = b.AvatarObjectKey
	return m0
}

type UpdateProfileRequest struct {
	state                 protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Id         string                      `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_UpdateMask *fieldmaskpb.FieldMask      `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3"`
	xxx_hidden_Identity   *claims.IdentityInformation `protobuf:"bytes,3,opt,name=identity,proto3,oneof"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateProfileRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *UpdateProfileRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.xxx_hidden_UpdateMask
	}
	return nil
}

func (x *UpdateProfileRequest) GetIdentity() *claims.IdentityInformation {
	if x != nil {
		return x.xxx_hidden_Identity
	}
	return nil
}

func (x *UpdateProfileRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *UpdateProfileRequest) SetUpdateMask(v *fieldmaskpb.FieldMask) {
	x.xxx_hidden_UpdateMask = v
}

func (x *UpdateProfileRequest) SetIdentity(v *claims.IdentityInformation) {
	x.xxx_hidden_Identity = v
}

func (x *UpdateProfileRequest) HasUpdateMask() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdateMask != nil
}

func (x *UpdateProfileRequest) HasIdentity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Identity != nil
}

func (x *UpdateProfileRequest) ClearUpdateMask() {
	x.xxx_hidden_UpdateMask = nil
}

func (x *UpdateProfileRequest) ClearIdentity() {
	x.xxx_hidden_Identity = nil
}

type UpdateProfileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
	// Mask paths are relative to this message: proto snake_case prefix `identity.` for
	// IdentityInformation fields (e.g. "identity.email", "identity.name", "identity.username").
	// JSON clients may send camelCase in the second segment (e.g. "identity.emailVerified");
	// the server normalizes to canonical snake_case paths.
	UpdateMask *fieldmaskpb.FieldMask
	// Values for fields listed in update_mask; only allowlisted paths are applied.
	Identity *claims.IdentityInformation
}

func (b0 UpdateProfileRequest_builder) Build() *UpdateProfileRequest {
	m0 := &UpdateProfileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_UpdateMask = b.UpdateMask
	x.xxx_hidden_Identity = b.Identity
	return m0
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateProfileResponse) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *UpdateProfileResponse) SetId(v string) {
	x.xxx_hidden_Id = v
}

type UpdateProfileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 UpdateProfileResponse_builder) Build() *UpdateProfileResponse {
	m0 := &UpdateProfileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type StartAvatarUploadRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_ContentType string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartAvatarUploadRequest) Reset() {
	*x = StartAvatarUploadRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAvatarUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAvatarUploadRequest) ProtoMessage() {}

func (x *StartAvatarUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartAvatarUploadRequest) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *StartAvatarUploadRequest) GetContentType() string {
	if x != nil {
		return x.xxx_hidden_ContentType
	}
	return ""
}

func (x *StartAvatarUploadRequest) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *StartAvatarUploadRequest) SetContentType(v string) {
	x.xxx_hidden_ContentType = v
}

type StartAvatarUploadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId      string
	ContentType string
}

func (b0 StartAvatarUploadRequest_builder) Build() *StartAvatarUploadRequest {
	m0 := &StartAvatarUploadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_ContentType = b.ContentType
	return m0
}

type StartAvatarUploadResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UploadUrl string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3"`
	xxx_hidden_ObjectKey string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3"`
	xxx_hidden_ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartAvatarUploadResponse) Reset() {
	*x = StartAvatarUploadResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAvatarUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAvatarUploadResponse) ProtoMessage() {}

func (x *StartAvatarUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartAvatarUploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.xxx_hidden_UploadUrl
	}
	return ""
}

func (x *StartAvatarUploadResponse) GetObjectKey() string {
	if x != nil {
		return x.xxx_hidden_ObjectKey
	}
	return ""
}

func (x *StartAvatarUploadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *StartAvatarUploadResponse) SetUploadUrl(v string) {
	x.xxx_hidden_UploadUrl = v
}

func (x *StartAvatarUploadResponse) SetObjectKey(v string) {
	x.xxx_hidden_ObjectKey = v
}

func (x *StartAvatarUploadResponse) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *StartAvatarUploadResponse) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *StartAvatarUploadResponse) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

type StartAvatarUploadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UploadUrl string
	ObjectKey string
	ExpiresAt *timestamppb.Timestamp
}

func (b0 StartAvatarUploadResponse_builder) Build() *StartAvatarUploadResponse {
	m0 := &StartAvatarUploadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UploadUrl = b.UploadUrl
	x.xxx_hidden_ObjectKey = b.ObjectKey
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	return m0
}

type CompleteAvatarUploadRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_ObjectKey string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3"`
	xxx_hidden_ByteSize  int64                  `protobuf:"varint,3,opt,name=byte_size,json=byteSize,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CompleteAvatarUploadRequest) Reset() {
	*x = CompleteAvatarUploadRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAvatarUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAvatarUploadRequest) ProtoMessage() {}

func (x *CompleteAvatarUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompleteAvatarUploadRequest) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *CompleteAvatarUploadRequest) GetObjectKey() string {
	if x != nil {
		return x.xxx_hidden_ObjectKey
	}
	return ""
}

func (x *CompleteAvatarUploadRequest) GetByteSize() int64 {
	if x != nil {
		return x.xxx_hidden_ByteSize
	}
	return 0
}

func (x *CompleteAvatarUploadRequest) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *CompleteAvatarUploadRequest) SetObjectKey(v string) {
	x.xxx_hidden_ObjectKey = v
}

func (x *CompleteAvatarUploadRequest) SetByteSize(v int64) {
	x.xxx_hidden_ByteSize = v
}

type CompleteAvatarUploadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId    string
	ObjectKey string
	ByteSize  int64
}

func (b0 CompleteAvatarUploadRequest_builder) Build() *CompleteAvatarUploadRequest {
	m0 := &CompleteAvatarUploadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_ObjectKey = b.ObjectKey
	x.xxx_hidden_ByteSize = b.ByteSize
	return m0
}

type CompleteAvatarUploadResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AvatarUrl string                 `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CompleteAvatarUploadResponse) Reset() {
	*x = CompleteAvatarUploadResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAvatarUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAvatarUploadResponse) ProtoMessage() {}

func (x *CompleteAvatarUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompleteAvatarUploadResponse) GetAvatarUrl() string {
	if x != nil {
		return x.xxx_hidden_AvatarUrl
	}
	return ""
}

func (x *CompleteAvatarUploadResponse) SetAvatarUrl(v string) {
	x.xxx_hidden_AvatarUrl = v
}

type CompleteAvatarUploadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AvatarUrl string
}

func (b0 CompleteAvatarUploadResponse_builder) Build() *CompleteAvatarUploadResponse {
	m0 := &CompleteAvatarUploadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AvatarUrl = b.AvatarUrl
	return m0
}

var File_profile_v1_profile_proto protoreflect.FileDescriptor

const file_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x18profile/v1/profile.proto\x12\x0fmuid.profile.v1\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\x1a\x16shared/v1/claims.proto\"\x8f\x01\n" +
	"\x14CreateProfileRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12K\n" +
	"\bidentity\x18\x02 \x01(\v2*.muid.shared.v1.claims.IdentityInformationH\x00R\bidentity\x88\x01\x01B\v\n" +
	"\t_identity\"1\n" +
	"\x15CreateProfileResponse\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"-\n" +
	"\x11GetProfileRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x83\x02\n" +
	"\x12GetProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12A\n" +
	"\busername\x18\x04 \x01(\tB%\xbaH\"r \x10\x05\x18\x102\x1a^[a-z0-9][a-z0-9_.]{4,15}$R\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06locale\x18\x06 \x01(\tR\x06locale\x12*\n" +
	"\x11avatar_object_key\x18\a \x01(\tR\x0favatarObjectKey\"\xc7\x01\n" +
	"\x14UpdateProfileRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12K\n" +
	"\bidentity\x18\x03 \x01(\v2*.muid.shared.v1.claims.IdentityInformationH\x00R\bidentity\x88\x01\x01B\v\n" +
	"\t_identity\"1\n" +
	"\x15UpdateProfileResponse\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"l\n" +
	"\x18StartAvatarUploadRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12-\n" +
	"\fcontent_type\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x03\x18\x80\x01R\vcontentType\"\x94\x01\n" +
	"\x19StartAvatarUploadResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x91\x01\n" +
	"\x1bCompleteAvatarUploadRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12)\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x04R\tobjectKey\x12$\n" +
	"\tbyte_size\x18\x03 \x01(\x03B\a\xbaH\x04\"\x02(\x01R\bbyteSize\"=\n" +
	"\x1cCompleteAvatarUploadResponse\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x01 \x01(\tR\tavatarUrl2\x88\x04\n" +
	"\x0eProfileService\x12^\n" +
	"\rCreateProfile\x12%.muid.profile.v1.CreateProfileRequest\x1a&.muid.profile.v1.CreateProfileResponse\x12U\n" +
	"\n" +
	"GetProfile\x12\".muid.profile.v1.GetProfileRequest\x1a#.muid.profile.v1.GetProfileResponse\x12^\n" +
	"\rUpdateProfile\x12%.muid.profile.v1.UpdateProfileRequest\x1a&.muid.profile.v1.UpdateProfileResponse\x12j\n" +
	"\x11StartAvatarUpload\x12).muid.profile.v1.StartAvatarUploadRequest\x1a*.muid.profile.v1.StartAvatarUploadResponse\x12s\n" +
	"\x14CompleteAvatarUpload\x12,.muid.profile.v1.CompleteAvatarUploadRequest\x1a-.muid.profile.v1.CompleteAvatarUploadResponseB\xad\x01\n" +
	"\x13com.muid.profile.v1B\fProfileProtoP\x01Z*sanzi.io/muid/api/proto/profile/v1;profile\xa2\x02\x03MPX\xaa\x02\x0fMuid.Profile.V1\xca\x02\x0fMuid\\Profile\\V1\xe2\x02\x1bMuid\\Profile\\V1\\GPBMetadata\xea\x02\x11Muid::Profile::V1b\x06proto3"

var file_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_profile_v1_profile_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),         // 0: muid.profile.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),        // 1: muid.profile.v1.CreateProfileResponse
	(*GetProfileRequest)(nil),            // 2: muid.profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),           // 3: muid.profile.v1.GetProfileResponse
	(*UpdateProfileRequest)(nil),         // 4: muid.profile.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),        // 5: muid.profile.v1.UpdateProfileResponse
	(*StartAvatarUploadRequest)(nil),     // 6: muid.profile.v1.StartAvatarUploadRequest
	(*StartAvatarUploadResponse)(nil),    // 7: muid.profile.v1.StartAvatarUploadResponse
	(*CompleteAvatarUploadRequest)(nil),  // 8: muid.profile.v1.CompleteAvatarUploadRequest
	(*CompleteAvatarUploadResponse)(nil), // 9: muid.profile.v1.CompleteAvatarUploadResponse
	(*claims.IdentityInformation)(nil),   // 10: muid.shared.v1.claims.IdentityInformation
	(*fieldmaskpb.FieldMask)(nil),        // 11: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
}
var file_profile_v1_profile_proto_depIdxs = []int32{
	10, // 0: muid.profile.v1.CreateProfileRequest.identity:type_name -> muid.shared.v1.claims.IdentityInformation
	11, // 1: muid.profile.v1.UpdateProfileRequest.update_mask:type_name -> google.protobuf.FieldMask
	10, // 2: muid.profile.v1.UpdateProfileRequest.identity:type_name -> muid.shared.v1.claims.IdentityInformation
	12, // 3: muid.profile.v1.StartAvatarUploadResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 4: muid.profile.v1.ProfileService.CreateProfile:input_type -> muid.profile.v1.CreateProfileRequest
	2,  // 5: muid.profile.v1.ProfileService.GetProfile:input_type -> muid.profile.v1.GetProfileRequest
	4,  // 6: muid.profile.v1.ProfileService.UpdateProfile:input_type -> muid.profile.v1.UpdateProfileRequest
	6,  // 7: muid.profile.v1.ProfileService.StartAvatarUpload:input_type -> muid.profile.v1.StartAvatarUploadRequest
	8,  // 8: muid.profile.v1.ProfileService.CompleteAvatarUpload:input_type -> muid.profile.v1.CompleteAvatarUploadRequest
	1,  // 9: muid.profile.v1.ProfileService.CreateProfile:output_type -> muid.profile.v1.CreateProfileResponse
	3,  // 10: muid.profile.v1.ProfileService.GetProfile:output_type -> muid.profile.v1.GetProfileResponse
	5,  // 11: muid.profile.v1.ProfileService.UpdateProfile:output_type -> muid.profile.v1.UpdateProfileResponse
	7,  // 12: muid.profile.v1.ProfileService.StartAvatarUpload:output_type -> muid.profile.v1.StartAvatarUploadResponse
	9,  // 13: muid.profile.v1.ProfileService.CompleteAvatarUpload:output_type -> muid.profile.v1.CompleteAvatarUploadResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_profile_v1_profile_proto_init() }
func file_profile_v1_profile_proto_init() {
	if File_profile_v1_profile_proto != nil {
		return
	}
	file_profile_v1_profile_proto_msgTypes[0].OneofWrappers = []any{}
	file_profile_v1_profile_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_profile_v1_profile_proto = out.File
	file_profile_v1_profile_proto_goTypes = nil
	file_profile_v1_profile_proto_depIdxs = nil
}
