// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authn/v1/authn.proto

package authn

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	basic "sanzi.io/muid/api/proto/authn/v1/basic"
	challenge "sanzi.io/muid/api/proto/authn/v1/challenge"
	proof "sanzi.io/muid/api/proto/authn/v1/proof"
	session "sanzi.io/muid/api/proto/authn/v1/session"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartAuthSessionRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Method     basic.AuthMethod       `protobuf:"varint,1,opt,name=method,proto3,enum=muid.authn.v1.basic.AuthMethod"`
	xxx_hidden_Identifier string                 `protobuf:"bytes,2,opt,name=identifier,proto3"`
	xxx_hidden_Intent     basic.AuthIntent       `protobuf:"varint,3,opt,name=intent,proto3,enum=muid.authn.v1.basic.AuthIntent"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StartAuthSessionRequest) Reset() {
	*x = StartAuthSessionRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAuthSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAuthSessionRequest) ProtoMessage() {}

func (x *StartAuthSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartAuthSessionRequest) GetMethod() basic.AuthMethod {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return basic.AuthMethod(0)
}

func (x *StartAuthSessionRequest) GetIdentifier() string {
	if x != nil {
		return x.xxx_hidden_Identifier
	}
	return ""
}

func (x *StartAuthSessionRequest) GetIntent() basic.AuthIntent {
	if x != nil {
		return x.xxx_hidden_Intent
	}
	return basic.AuthIntent(0)
}

func (x *StartAuthSessionRequest) SetMethod(v basic.AuthMethod) {
	x.xxx_hidden_Method = v
}

func (x *StartAuthSessionRequest) SetIdentifier(v string) {
	x.xxx_hidden_Identifier = v
}

func (x *StartAuthSessionRequest) SetIntent(v basic.AuthIntent) {
	x.xxx_hidden_Intent = v
}

type StartAuthSessionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Method     basic.AuthMethod
	Identifier string
	// intent defaults to AUTH_INTENT_LOGIN when unset.
	Intent basic.AuthIntent
}

func (b0 StartAuthSessionRequest_builder) Build() *StartAuthSessionRequest {
	m0 := &StartAuthSessionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Method = b.Method
	x.xxx_hidden_Identifier = b.Identifier
	x.xxx_hidden_Intent = b.Intent
	return m0
}

type StartAuthSessionResponse struct {
	state                   protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_TransitionId string                   `protobuf:"bytes,1,opt,name=transition_id,json=transitionId,proto3"`
	xxx_hidden_Challenge    *challenge.AuthChallenge `protobuf:"bytes,2,opt,name=challenge,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StartAuthSessionResponse) Reset() {
	*x = StartAuthSessionResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAuthSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAuthSessionResponse) ProtoMessage() {}

func (x *StartAuthSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartAuthSessionResponse) GetTransitionId() string {
	if x != nil {
		return x.xxx_hidden_TransitionId
	}
	return ""
}

func (x *StartAuthSessionResponse) GetChallenge() *challenge.AuthChallenge {
	if x != nil {
		return x.xxx_hidden_Challenge
	}
	return nil
}

func (x *StartAuthSessionResponse) SetTransitionId(v string) {
	x.xxx_hidden_TransitionId = v
}

func (x *StartAuthSessionResponse) SetChallenge(v *challenge.AuthChallenge) {
	x.xxx_hidden_Challenge = v
}

func (x *StartAuthSessionResponse) HasChallenge() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Challenge != nil
}

func (x *StartAuthSessionResponse) ClearChallenge() {
	x.xxx_hidden_Challenge = nil
}

type StartAuthSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TransitionId string
	Challenge    *challenge.AuthChallenge
}

func (b0 StartAuthSessionResponse_builder) Build() *StartAuthSessionResponse {
	m0 := &StartAuthSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TransitionId = b.TransitionId
	x.xxx_hidden_Challenge = b.Challenge
	return m0
}

type ContinueAuthSessionRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TransitionId string                 `protobuf:"bytes,1,opt,name=transition_id,json=transitionId,proto3"`
	xxx_hidden_Proof        *proof.AuthProof       `protobuf:"bytes,2,opt,name=proof,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ContinueAuthSessionRequest) Reset() {
	*x = ContinueAuthSessionRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueAuthSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueAuthSessionRequest) ProtoMessage() {}

func (x *ContinueAuthSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContinueAuthSessionRequest) GetTransitionId() string {
	if x != nil {
		return x.xxx_hidden_TransitionId
	}
	return ""
}

func (x *ContinueAuthSessionRequest) GetProof() *proof.AuthProof {
	if x != nil {
		return x.xxx_hidden_Proof
	}
	return nil
}

func (x *ContinueAuthSessionRequest) SetTransitionId(v string) {
	x.xxx_hidden_TransitionId = v
}

func (x *ContinueAuthSessionRequest) SetProof(v *proof.AuthProof) {
	x.xxx_hidden_Proof = v
}

func (x *ContinueAuthSessionRequest) HasProof() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Proof != nil
}

func (x *ContinueAuthSessionRequest) ClearProof() {
	x.xxx_hidden_Proof = nil
}

type ContinueAuthSessionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TransitionId string
	Proof        *proof.AuthProof
}

func (b0 ContinueAuthSessionRequest_builder) Build() *ContinueAuthSessionRequest {
	m0 := &ContinueAuthSessionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TransitionId = b.TransitionId
	x.xxx_hidden_Proof = b.Proof
	return m0
}

type ContinueAuthSessionResponse struct {
	state                   protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_TransitionId string                               `protobuf:"bytes,1,opt,name=transition_id,json=transitionId,proto3"`
	xxx_hidden_Status       basic.AuthStatus                     `protobuf:"varint,2,opt,name=status,proto3,enum=muid.authn.v1.basic.AuthStatus"`
	xxx_hidden_Result       isContinueAuthSessionResponse_Result `protobuf_oneof:"result"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ContinueAuthSessionResponse) Reset() {
	*x = ContinueAuthSessionResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueAuthSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueAuthSessionResponse) ProtoMessage() {}

func (x *ContinueAuthSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContinueAuthSessionResponse) GetTransitionId() string {
	if x != nil {
		return x.xxx_hidden_TransitionId
	}
	return ""
}

func (x *ContinueAuthSessionResponse) GetStatus() basic.AuthStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return basic.AuthStatus(0)
}

func (x *ContinueAuthSessionResponse) GetChallengeRequired() *session.ChallengeRequired {
	if x != nil {
		if x, ok := x.xxx_hidden_Result.(*continueAuthSessionResponse_ChallengeRequired); ok {
			return x.ChallengeRequired
		}
	}
	return nil
}

func (x *ContinueAuthSessionResponse) GetAuthSuccess() *session.AuthSuccess {
	if x != nil {
		if x, ok := x.xxx_hidden_Result.(*continueAuthSessionResponse_AuthSuccess); ok {
			return x.AuthSuccess
		}
	}
	return nil
}

func (x *ContinueAuthSessionResponse) SetTransitionId(v string) {
	x.xxx_hidden_TransitionId = v
}

func (x *ContinueAuthSessionResponse) SetStatus(v basic.AuthStatus) {
	x.xxx_hidden_Status = v
}

func (x *ContinueAuthSessionResponse) SetChallengeRequired(v *session.ChallengeRequired) {
	if v == nil {
		x.xxx_hidden_Result = nil
		return
	}
	x.xxx_hidden_Result = &continueAuthSessionResponse_ChallengeRequired{v}
}

func (x *ContinueAuthSessionResponse) SetAuthSuccess(v *session.AuthSuccess) {
	if v == nil {
		x.xxx_hidden_Result = nil
		return
	}
	x.xxx_hidden_Result = &continueAuthSessionResponse_AuthSuccess{v}
}

func (x *ContinueAuthSessionResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *ContinueAuthSessionResponse) HasChallengeRequired() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Result.(*continueAuthSessionResponse_ChallengeRequired)
	return ok
}

func (x *ContinueAuthSessionResponse) HasAuthSuccess() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Result.(*continueAuthSessionResponse_AuthSuccess)
	return ok
}

func (x *ContinueAuthSessionResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

func (x *ContinueAuthSessionResponse) ClearChallengeRequired() {
	if _, ok := x.xxx_hidden_Result.(*continueAuthSessionResponse_ChallengeRequired); ok {
		x.xxx_hidden_Result = nil
	}
}

func (x *ContinueAuthSessionResponse) ClearAuthSuccess() {
	if _, ok := x.xxx_hidden_Result.(*continueAuthSessionResponse_AuthSuccess); ok {
		x.xxx_hidden_Result = nil
	}
}

const ContinueAuthSessionResponse_Result_not_set_case case_ContinueAuthSessionResponse_Result = 0
const ContinueAuthSessionResponse_ChallengeRequired_case case_ContinueAuthSessionResponse_Result = 3
const ContinueAuthSessionResponse_AuthSuccess_case case_ContinueAuthSessionResponse_Result = 4

func (x *ContinueAuthSessionResponse) WhichResult() case_ContinueAuthSessionResponse_Result {
	if x == nil {
		return ContinueAuthSessionResponse_Result_not_set_case
	}
	switch x.xxx_hidden_Result.(type) {
	case *continueAuthSessionResponse_ChallengeRequired:
		return ContinueAuthSessionResponse_ChallengeRequired_case
	case *continueAuthSessionResponse_AuthSuccess:
		return ContinueAuthSessionResponse_AuthSuccess_case
	default:
		return ContinueAuthSessionResponse_Result_not_set_case
	}
}

type ContinueAuthSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TransitionId string
	Status       basic.AuthStatus
	// Fields of oneof xxx_hidden_Result:
	ChallengeRequired *session.ChallengeRequired
	AuthSuccess       *session.AuthSuccess
	// -- end of xxx_hidden_Result
}

func (b0 ContinueAuthSessionResponse_builder) Build() *ContinueAuthSessionResponse {
	m0 := &ContinueAuthSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TransitionId = b.TransitionId
	x.xxx_hidden_Status = b.Status
	if b.ChallengeRequired != nil {
		x.xxx_hidden_Result = &continueAuthSessionResponse_ChallengeRequired{b.ChallengeRequired}
	}
	if b.AuthSuccess != nil {
		x.xxx_hidden_Result = &continueAuthSessionResponse_AuthSuccess{b.AuthSuccess}
	}
	return m0
}

type case_ContinueAuthSessionResponse_Result protoreflect.FieldNumber

func (x case_ContinueAuthSessionResponse_Result) String() string {
	md := file_authn_v1_authn_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isContinueAuthSessionResponse_Result interface {
	isContinueAuthSessionResponse_Result()
}

type continueAuthSessionResponse_ChallengeRequired struct {
	ChallengeRequired *session.ChallengeRequired `protobuf:"bytes,3,opt,name=challenge_required,json=challengeRequired,proto3,oneof"`
}

type continueAuthSessionResponse_AuthSuccess struct {
	AuthSuccess *session.AuthSuccess `protobuf:"bytes,4,opt,name=auth_success,json=authSuccess,proto3,oneof"` // field 5 (auth_failure) removed: failures are now gRPC errors with AuthFailure as error detail
}

func (*continueAuthSessionResponse_ChallengeRequired) isContinueAuthSessionResponse_Result() {}

func (*continueAuthSessionResponse_AuthSuccess) isContinueAuthSessionResponse_Result() {}

// Session token is passed via the authorization metadata header: "Session <token>".
type GetAuthorizedSessionRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorizedSessionRequest) Reset() {
	*x = GetAuthorizedSessionRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizedSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizedSessionRequest) ProtoMessage() {}

func (x *GetAuthorizedSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetAuthorizedSessionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetAuthorizedSessionRequest_builder) Build() *GetAuthorizedSessionRequest {
	m0 := &GetAuthorizedSessionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetAuthorizedSessionResponse struct {
	state              protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Valid   bool                         `protobuf:"varint,1,opt,name=valid,proto3"`
	xxx_hidden_Session *session.AuthenticatedResult `protobuf:"bytes,2,opt,name=session,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAuthorizedSessionResponse) Reset() {
	*x = GetAuthorizedSessionResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizedSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizedSessionResponse) ProtoMessage() {}

func (x *GetAuthorizedSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAuthorizedSessionResponse) GetValid() bool {
	if x != nil {
		return x.xxx_hidden_Valid
	}
	return false
}

func (x *GetAuthorizedSessionResponse) GetSession() *session.AuthenticatedResult {
	if x != nil {
		return x.xxx_hidden_Session
	}
	return nil
}

func (x *GetAuthorizedSessionResponse) SetValid(v bool) {
	x.xxx_hidden_Valid = v
}

func (x *GetAuthorizedSessionResponse) SetSession(v *session.AuthenticatedResult) {
	x.xxx_hidden_Session = v
}

func (x *GetAuthorizedSessionResponse) HasSession() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Session != nil
}

func (x *GetAuthorizedSessionResponse) ClearSession() {
	x.xxx_hidden_Session = nil
}

type GetAuthorizedSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Valid   bool
	Session *session.AuthenticatedResult
}

func (b0 GetAuthorizedSessionResponse_builder) Build() *GetAuthorizedSessionResponse {
	m0 := &GetAuthorizedSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Valid = b.Valid
	x.xxx_hidden_Session = b.Session
	return m0
}

// Session token is passed via the authorization metadata header: "Session <token>".
type GetAuthenticatedPrincipalRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthenticatedPrincipalRequest) Reset() {
	*x = GetAuthenticatedPrincipalRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthenticatedPrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthenticatedPrincipalRequest) ProtoMessage() {}

func (x *GetAuthenticatedPrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetAuthenticatedPrincipalRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetAuthenticatedPrincipalRequest_builder) Build() *GetAuthenticatedPrincipalRequest {
	m0 := &GetAuthenticatedPrincipalRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetAuthenticatedPrincipalResponse struct {
	state                protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Valid     bool                            `protobuf:"varint,1,opt,name=valid,proto3"`
	xxx_hidden_Principal *session.AuthenticatedPrincipal `protobuf:"bytes,2,opt,name=principal,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetAuthenticatedPrincipalResponse) Reset() {
	*x = GetAuthenticatedPrincipalResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthenticatedPrincipalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthenticatedPrincipalResponse) ProtoMessage() {}

func (x *GetAuthenticatedPrincipalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAuthenticatedPrincipalResponse) GetValid() bool {
	if x != nil {
		return x.xxx_hidden_Valid
	}
	return false
}

func (x *GetAuthenticatedPrincipalResponse) GetPrincipal() *session.AuthenticatedPrincipal {
	if x != nil {
		return x.xxx_hidden_Principal
	}
	return nil
}

func (x *GetAuthenticatedPrincipalResponse) SetValid(v bool) {
	x.xxx_hidden_Valid = v
}

func (x *GetAuthenticatedPrincipalResponse) SetPrincipal(v *session.AuthenticatedPrincipal) {
	x.xxx_hidden_Principal = v
}

func (x *GetAuthenticatedPrincipalResponse) HasPrincipal() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Principal != nil
}

func (x *GetAuthenticatedPrincipalResponse) ClearPrincipal() {
	x.xxx_hidden_Principal = nil
}

type GetAuthenticatedPrincipalResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Valid     bool
	Principal *session.AuthenticatedPrincipal
}

func (b0 GetAuthenticatedPrincipalResponse_builder) Build() *GetAuthenticatedPrincipalResponse {
	m0 := &GetAuthenticatedPrincipalResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Valid = b.Valid
	x.xxx_hidden_Principal = b.Principal
	return m0
}

// Session token is passed via the authorization metadata header: "Session <token>".
type RevokeFederatedIdentityRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RevokeFederatedIdentityRequest) Reset() {
	*x = RevokeFederatedIdentityRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeFederatedIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeFederatedIdentityRequest) ProtoMessage() {}

func (x *RevokeFederatedIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevokeFederatedIdentityRequest) GetProvider() string {
	if x != nil {
		return x.xxx_hidden_Provider
	}
	return ""
}

func (x *RevokeFederatedIdentityRequest) SetProvider(v string) {
	x.xxx_hidden_Provider = v
}

type RevokeFederatedIdentityRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Provider string
}

func (b0 RevokeFederatedIdentityRequest_builder) Build() *RevokeFederatedIdentityRequest {
	m0 := &RevokeFederatedIdentityRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Provider = b.Provider
	return m0
}

type RevokeFederatedIdentityResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success bool                   `protobuf:"varint,1,opt,name=success,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RevokeFederatedIdentityResponse) Reset() {
	*x = RevokeFederatedIdentityResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeFederatedIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeFederatedIdentityResponse) ProtoMessage() {}

func (x *RevokeFederatedIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevokeFederatedIdentityResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *RevokeFederatedIdentityResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
}

type RevokeFederatedIdentityResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success bool
}

func (b0 RevokeFederatedIdentityResponse_builder) Build() *RevokeFederatedIdentityResponse {
	m0 := &RevokeFederatedIdentityResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Success = b.Success
	return m0
}

// Session token is passed via the authorization metadata header: "Session <token>".
type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RevokeSessionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RevokeSessionRequest_builder) Build() *RevokeSessionRequest {
	m0 := &RevokeSessionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RevokeSessionResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success bool                   `protobuf:"varint,1,opt,name=success,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevokeSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *RevokeSessionResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
}

type RevokeSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success bool
}

func (b0 RevokeSessionResponse_builder) Build() *RevokeSessionResponse {
	m0 := &RevokeSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Success = b.Success
	return m0
}

// Session token is passed via the authorization metadata header: "Session <token>".
type ExtendSessionRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendSessionRequest) Reset() {
	*x = ExtendSessionRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendSessionRequest) ProtoMessage() {}

func (x *ExtendSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ExtendSessionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ExtendSessionRequest_builder) Build() *ExtendSessionRequest {
	m0 := &ExtendSessionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ExtendSessionResponse struct {
	state                     protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_SessionContext *session.SessionContext `protobuf:"bytes,1,opt,name=session_context,json=sessionContext,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ExtendSessionResponse) Reset() {
	*x = ExtendSessionResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendSessionResponse) ProtoMessage() {}

func (x *ExtendSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExtendSessionResponse) GetSessionContext() *session.SessionContext {
	if x != nil {
		return x.xxx_hidden_SessionContext
	}
	return nil
}

func (x *ExtendSessionResponse) SetSessionContext(v *session.SessionContext) {
	x.xxx_hidden_SessionContext = v
}

func (x *ExtendSessionResponse) HasSessionContext() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SessionContext != nil
}

func (x *ExtendSessionResponse) ClearSessionContext() {
	x.xxx_hidden_SessionContext = nil
}

type ExtendSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionContext *session.SessionContext
}

func (b0 ExtendSessionResponse_builder) Build() *ExtendSessionResponse {
	m0 := &ExtendSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SessionContext = b.SessionContext
	return m0
}

var File_authn_v1_authn_proto protoreflect.FileDescriptor

const file_authn_v1_authn_proto_rawDesc = "" +
	"\n" +
	"\x14authn/v1/authn.proto\x12\rmuid.authn.v1\x1a\x14authn/v1/basic.proto\x1a\x18authn/v1/challenge.proto\x1a\x14authn/v1/proof.proto\x1a\x16authn/v1/session.proto\x1a\x1bbuf/validate/validate.proto\"\xb5\x01\n" +
	"\x17StartAuthSessionRequest\x127\n" +
	"\x06method\x18\x01 \x01(\x0e2\x1f.muid.authn.v1.basic.AuthMethodR\x06method\x12(\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\n" +
	"identifier\x127\n" +
	"\x06intent\x18\x03 \x01(\x0e2\x1f.muid.authn.v1.basic.AuthIntentR\x06intent\"\x8f\x01\n" +
	"\x18StartAuthSessionResponse\x12-\n" +
	"\rtransition_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ftransitionId\x12D\n" +
	"\tchallenge\x18\x02 \x01(\v2&.muid.authn.v1.challenge.AuthChallengeR\tchallenge\"\x81\x01\n" +
	"\x1aContinueAuthSessionRequest\x12-\n" +
	"\rtransition_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ftransitionId\x124\n" +
	"\x05proof\x18\x02 \x01(\v2\x1e.muid.authn.v1.proof.AuthProofR\x05proof\"\xb3\x02\n" +
	"\x1bContinueAuthSessionResponse\x12-\n" +
	"\rtransition_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ftransitionId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.muid.authn.v1.basic.AuthStatusR\x06status\x12Y\n" +
	"\x12challenge_required\x18\x03 \x01(\v2(.muid.authn.v1.session.ChallengeRequiredH\x00R\x11challengeRequired\x12G\n" +
	"\fauth_success\x18\x04 \x01(\v2\".muid.authn.v1.session.AuthSuccessH\x00R\vauthSuccessB\b\n" +
	"\x06result\"\x1d\n" +
	"\x1bGetAuthorizedSessionRequest\"z\n" +
	"\x1cGetAuthorizedSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12D\n" +
	"\asession\x18\x02 \x01(\v2*.muid.authn.v1.session.AuthenticatedResultR\asession\"\"\n" +
	" GetAuthenticatedPrincipalRequest\"\x86\x01\n" +
	"!GetAuthenticatedPrincipalResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12K\n" +
	"\tprincipal\x18\x02 \x01(\v2-.muid.authn.v1.session.AuthenticatedPrincipalR\tprincipal\"G\n" +
	"\x1eRevokeFederatedIdentityRequest\x12%\n" +
	"\bprovider\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\bprovider\";\n" +
	"\x1fRevokeFederatedIdentityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x16\n" +
	"\x14RevokeSessionRequest\"1\n" +
	"\x15RevokeSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x16\n" +
	"\x14ExtendSessionRequest\"g\n" +
	"\x15ExtendSessionResponse\x12N\n" +
	"\x0fsession_context\x18\x01 \x01(\v2%.muid.authn.v1.session.SessionContextR\x0esessionContext2\x84\x06\n" +
	"\fAuthnService\x12c\n" +
	"\x10StartAuthSession\x12&.muid.authn.v1.StartAuthSessionRequest\x1a'.muid.authn.v1.StartAuthSessionResponse\x12l\n" +
	"\x13ContinueAuthSession\x12).muid.authn.v1.ContinueAuthSessionRequest\x1a*.muid.authn.v1.ContinueAuthSessionResponse\x12x\n" +
	"\x17RevokeFederatedIdentity\x12-.muid.authn.v1.RevokeFederatedIdentityRequest\x1a..muid.authn.v1.RevokeFederatedIdentityResponse\x12o\n" +
	"\x14GetAuthorizedSession\x12*.muid.authn.v1.GetAuthorizedSessionRequest\x1a+.muid.authn.v1.GetAuthorizedSessionResponse\x12~\n" +
	"\x19GetAuthenticatedPrincipal\x12/.muid.authn.v1.GetAuthenticatedPrincipalRequest\x1a0.muid.authn.v1.GetAuthenticatedPrincipalResponse\x12Z\n" +
	"\rRevokeSession\x12#.muid.authn.v1.RevokeSessionRequest\x1a$.muid.authn.v1.RevokeSessionResponse\x12Z\n" +
	"\rExtendSession\x12#.muid.authn.v1.ExtendSessionRequest\x1a$.muid.authn.v1.ExtendSessionResponseB\x9d\x01\n" +
	"\x11com.muid.authn.v1B\n" +
	"AuthnProtoP\x01Z&sanzi.io/muid/api/proto/authn/v1;authn\xa2\x02\x03MAX\xaa\x02\rMuid.Authn.V1\xca\x02\rMuid\\Authn\\V1\xe2\x02\x19Muid\\Authn\\V1\\GPBMetadata\xea\x02\x0fMuid::Authn::V1b\x06proto3"

var file_authn_v1_authn_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_authn_v1_authn_proto_goTypes = []any{
	(*StartAuthSessionRequest)(nil),           // 0: muid.authn.v1.StartAuthSessionRequest
	(*StartAuthSessionResponse)(nil),          // 1: muid.authn.v1.StartAuthSessionResponse
	(*ContinueAuthSessionRequest)(nil),        // 2: muid.authn.v1.ContinueAuthSessionRequest
	(*ContinueAuthSessionResponse)(nil),       // 3: muid.authn.v1.ContinueAuthSessionResponse
	(*GetAuthorizedSessionRequest)(nil),       // 4: muid.authn.v1.GetAuthorizedSessionRequest
	(*GetAuthorizedSessionResponse)(nil),      // 5: muid.authn.v1.GetAuthorizedSessionResponse
	(*GetAuthenticatedPrincipalRequest)(nil),  // 6: muid.authn.v1.GetAuthenticatedPrincipalRequest
	(*GetAuthenticatedPrincipalResponse)(nil), // 7: muid.authn.v1.GetAuthenticatedPrincipalResponse
	(*RevokeFederatedIdentityRequest)(nil),    // 8: muid.authn.v1.RevokeFederatedIdentityRequest
	(*RevokeFederatedIdentityResponse)(nil),   // 9: muid.authn.v1.RevokeFederatedIdentityResponse
	(*RevokeSessionRequest)(nil),              // 10: muid.authn.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),             // 11: muid.authn.v1.RevokeSessionResponse
	(*ExtendSessionRequest)(nil),              // 12: muid.authn.v1.ExtendSessionRequest
	(*ExtendSessionResponse)(nil),             // 13: muid.authn.v1.ExtendSessionResponse
	(basic.AuthMethod)(0),                     // 14: muid.authn.v1.basic.AuthMethod
	(basic.AuthIntent)(0),                     // 15: muid.authn.v1.basic.AuthIntent
	(*challenge.AuthChallenge)(nil),           // 16: muid.authn.v1.challenge.AuthChallenge
	(*proof.AuthProof)(nil),                   // 17: muid.authn.v1.proof.AuthProof
	(basic.AuthStatus)(0),                     // 18: muid.authn.v1.basic.AuthStatus
	(*session.ChallengeRequired)(nil),         // 19: muid.authn.v1.session.ChallengeRequired
	(*session.AuthSuccess)(nil),               // 20: muid.authn.v1.session.AuthSuccess
	(*session.AuthenticatedResult)(nil),       // 21: muid.authn.v1.session.AuthenticatedResult
	(*session.AuthenticatedPrincipal)(nil),    // 22: muid.authn.v1.session.AuthenticatedPrincipal
	(*session.SessionContext)(nil),            // 23: muid.authn.v1.session.SessionContext
}
var file_authn_v1_authn_proto_depIdxs = []int32{
	14, // 0: muid.authn.v1.StartAuthSessionRequest.method:type_name -> muid.authn.v1.basic.AuthMethod
	15, // 1: muid.authn.v1.StartAuthSessionRequest.intent:type_name -> muid.authn.v1.basic.AuthIntent
	16, // 2: muid.authn.v1.StartAuthSessionResponse.challenge:type_name -> muid.authn.v1.challenge.AuthChallenge
	17, // 3: muid.authn.v1.ContinueAuthSessionRequest.proof:type_name -> muid.authn.v1.proof.AuthProof
	18, // 4: muid.authn.v1.ContinueAuthSessionResponse.status:type_name -> muid.authn.v1.basic.AuthStatus
	19, // 5: muid.authn.v1.ContinueAuthSessionResponse.challenge_required:type_name -> muid.authn.v1.session.ChallengeRequired
	20, // 6: muid.authn.v1.ContinueAuthSessionResponse.auth_success:type_name -> muid.authn.v1.session.AuthSuccess
	21, // 7: muid.authn.v1.GetAuthorizedSessionResponse.session:type_name -> muid.authn.v1.session.AuthenticatedResult
	22, // 8: muid.authn.v1.GetAuthenticatedPrincipalResponse.principal:type_name -> muid.authn.v1.session.AuthenticatedPrincipal
	23, // 9: muid.authn.v1.ExtendSessionResponse.session_context:type_name -> muid.authn.v1.session.SessionContext
	0,  // 10: muid.authn.v1.AuthnService.StartAuthSession:input_type -> muid.authn.v1.StartAuthSessionRequest
	2,  // 11: muid.authn.v1.AuthnService.ContinueAuthSession:input_type -> muid.authn.v1.ContinueAuthSessionRequest
	8,  // 12: muid.authn.v1.AuthnService.RevokeFederatedIdentity:input_type -> muid.authn.v1.RevokeFederatedIdentityRequest
	4,  // 13: muid.authn.v1.AuthnService.GetAuthorizedSession:input_type -> muid.authn.v1.GetAuthorizedSessionRequest
	6,  // 14: muid.authn.v1.AuthnService.GetAuthenticatedPrincipal:input_type -> muid.authn.v1.GetAuthenticatedPrincipalRequest
	10, // 15: muid.authn.v1.AuthnService.RevokeSession:input_type -> muid.authn.v1.RevokeSessionRequest
	12, // 16: muid.authn.v1.AuthnService.ExtendSession:input_type -> muid.authn.v1.ExtendSessionRequest
	1,  // 17: muid.authn.v1.AuthnService.StartAuthSession:output_type -> muid.authn.v1.StartAuthSessionResponse
	3,  // 18: muid.authn.v1.AuthnService.ContinueAuthSession:output_type -> muid.authn.v1.ContinueAuthSessionResponse
	9,  // 19: muid.authn.v1.AuthnService.RevokeFederatedIdentity:output_type -> muid.authn.v1.RevokeFederatedIdentityResponse
	5,  // 20: muid.authn.v1.AuthnService.GetAuthorizedSession:output_type -> muid.authn.v1.GetAuthorizedSessionResponse
	7,  // 21: muid.authn.v1.AuthnService.GetAuthenticatedPrincipal:output_type -> muid.authn.v1.GetAuthenticatedPrincipalResponse
	11, // 22: muid.authn.v1.AuthnService.RevokeSession:output_type -> muid.authn.v1.RevokeSessionResponse
	13, // 23: muid.authn.v1.AuthnService.ExtendSession:output_type -> muid.authn.v1.ExtendSessionResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_authn_v1_authn_proto_init() }
func file_authn_v1_authn_proto_init() {
	if File_authn_v1_authn_proto != nil {
		return
	}
	file_authn_v1_authn_proto_msgTypes[3].OneofWrappers = []any{
		(*continueAuthSessionResponse_ChallengeRequired)(nil),
		(*continueAuthSessionResponse_AuthSuccess)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authn_v1_authn_proto_rawDesc), len(file_authn_v1_authn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authn_v1_authn_proto_goTypes,
		DependencyIndexes: file_authn_v1_authn_proto_depIdxs,
		MessageInfos:      file_authn_v1_authn_proto_msgTypes,
	}.Build()
	File_authn_v1_authn_proto = out.File
	file_authn_v1_authn_proto_goTypes = nil
	file_authn_v1_authn_proto_depIdxs = nil
}
