// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authn/v1/authentication_flow.proto

package authn

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	basic "sanzi.io/muid/api/proto/authn/v1/basic"
	challenge "sanzi.io/muid/api/proto/authn/v1/challenge"
	proof "sanzi.io/muid/api/proto/authn/v1/proof"
	session "sanzi.io/muid/api/proto/authn/v1/session"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartLoginRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Method     basic.AuthMethod       `protobuf:"varint,1,opt,name=method,proto3,enum=muid.authn.v1.basic.AuthMethod"`
	xxx_hidden_Identifier string                 `protobuf:"bytes,2,opt,name=identifier,proto3"`
	xxx_hidden_Intent     basic.AuthIntent       `protobuf:"varint,3,opt,name=intent,proto3,enum=muid.authn.v1.basic.AuthIntent"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StartLoginRequest) Reset() {
	*x = StartLoginRequest{}
	mi := &file_authn_v1_authentication_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginRequest) ProtoMessage() {}

func (x *StartLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authentication_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartLoginRequest) GetMethod() basic.AuthMethod {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return basic.AuthMethod(0)
}

func (x *StartLoginRequest) GetIdentifier() string {
	if x != nil {
		return x.xxx_hidden_Identifier
	}
	return ""
}

func (x *StartLoginRequest) GetIntent() basic.AuthIntent {
	if x != nil {
		return x.xxx_hidden_Intent
	}
	return basic.AuthIntent(0)
}

func (x *StartLoginRequest) SetMethod(v basic.AuthMethod) {
	x.xxx_hidden_Method = v
}

func (x *StartLoginRequest) SetIdentifier(v string) {
	x.xxx_hidden_Identifier = v
}

func (x *StartLoginRequest) SetIntent(v basic.AuthIntent) {
	x.xxx_hidden_Intent = v
}

type StartLoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Method     basic.AuthMethod
	Identifier string
	// intent defaults to AUTH_INTENT_LOGIN when unset.
	Intent basic.AuthIntent
}

func (b0 StartLoginRequest_builder) Build() *StartLoginRequest {
	m0 := &StartLoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Method = b.Method
	x.xxx_hidden_Identifier = b.Identifier
	x.xxx_hidden_Intent = b.Intent
	return m0
}

type StartLoginResponse struct {
	state                   protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_TransitionId string                   `protobuf:"bytes,1,opt,name=transition_id,json=transitionId,proto3"`
	xxx_hidden_Challenge    *challenge.AuthChallenge `protobuf:"bytes,2,opt,name=challenge,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StartLoginResponse) Reset() {
	*x = StartLoginResponse{}
	mi := &file_authn_v1_authentication_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginResponse) ProtoMessage() {}

func (x *StartLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authentication_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartLoginResponse) GetTransitionId() string {
	if x != nil {
		return x.xxx_hidden_TransitionId
	}
	return ""
}

func (x *StartLoginResponse) GetChallenge() *challenge.AuthChallenge {
	if x != nil {
		return x.xxx_hidden_Challenge
	}
	return nil
}

func (x *StartLoginResponse) SetTransitionId(v string) {
	x.xxx_hidden_TransitionId = v
}

func (x *StartLoginResponse) SetChallenge(v *challenge.AuthChallenge) {
	x.xxx_hidden_Challenge = v
}

func (x *StartLoginResponse) HasChallenge() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Challenge != nil
}

func (x *StartLoginResponse) ClearChallenge() {
	x.xxx_hidden_Challenge = nil
}

type StartLoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TransitionId string
	Challenge    *challenge.AuthChallenge
}

func (b0 StartLoginResponse_builder) Build() *StartLoginResponse {
	m0 := &StartLoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TransitionId = b.TransitionId
	x.xxx_hidden_Challenge = b.Challenge
	return m0
}

type ContinueLoginRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TransitionId string                 `protobuf:"bytes,1,opt,name=transition_id,json=transitionId,proto3"`
	xxx_hidden_Proof        *proof.AuthProof       `protobuf:"bytes,2,opt,name=proof,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ContinueLoginRequest) Reset() {
	*x = ContinueLoginRequest{}
	mi := &file_authn_v1_authentication_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueLoginRequest) ProtoMessage() {}

func (x *ContinueLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authentication_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContinueLoginRequest) GetTransitionId() string {
	if x != nil {
		return x.xxx_hidden_TransitionId
	}
	return ""
}

func (x *ContinueLoginRequest) GetProof() *proof.AuthProof {
	if x != nil {
		return x.xxx_hidden_Proof
	}
	return nil
}

func (x *ContinueLoginRequest) SetTransitionId(v string) {
	x.xxx_hidden_TransitionId = v
}

func (x *ContinueLoginRequest) SetProof(v *proof.AuthProof) {
	x.xxx_hidden_Proof = v
}

func (x *ContinueLoginRequest) HasProof() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Proof != nil
}

func (x *ContinueLoginRequest) ClearProof() {
	x.xxx_hidden_Proof = nil
}

type ContinueLoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TransitionId string
	Proof        *proof.AuthProof
}

func (b0 ContinueLoginRequest_builder) Build() *ContinueLoginRequest {
	m0 := &ContinueLoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TransitionId = b.TransitionId
	x.xxx_hidden_Proof = b.Proof
	return m0
}

type ContinueLoginResponse struct {
	state                   protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_TransitionId string                         `protobuf:"bytes,1,opt,name=transition_id,json=transitionId,proto3"`
	xxx_hidden_Status       basic.AuthStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=muid.authn.v1.basic.AuthStatus"`
	xxx_hidden_Result       isContinueLoginResponse_Result `protobuf_oneof:"result"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ContinueLoginResponse) Reset() {
	*x = ContinueLoginResponse{}
	mi := &file_authn_v1_authentication_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueLoginResponse) ProtoMessage() {}

func (x *ContinueLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authentication_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContinueLoginResponse) GetTransitionId() string {
	if x != nil {
		return x.xxx_hidden_TransitionId
	}
	return ""
}

func (x *ContinueLoginResponse) GetStatus() basic.AuthStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return basic.AuthStatus(0)
}

func (x *ContinueLoginResponse) GetChallengeRequired() *session.ChallengeRequired {
	if x != nil {
		if x, ok := x.xxx_hidden_Result.(*continueLoginResponse_ChallengeRequired); ok {
			return x.ChallengeRequired
		}
	}
	return nil
}

func (x *ContinueLoginResponse) GetAuthSuccess() *session.AuthSuccess {
	if x != nil {
		if x, ok := x.xxx_hidden_Result.(*continueLoginResponse_AuthSuccess); ok {
			return x.AuthSuccess
		}
	}
	return nil
}

func (x *ContinueLoginResponse) SetTransitionId(v string) {
	x.xxx_hidden_TransitionId = v
}

func (x *ContinueLoginResponse) SetStatus(v basic.AuthStatus) {
	x.xxx_hidden_Status = v
}

func (x *ContinueLoginResponse) SetChallengeRequired(v *session.ChallengeRequired) {
	if v == nil {
		x.xxx_hidden_Result = nil
		return
	}
	x.xxx_hidden_Result = &continueLoginResponse_ChallengeRequired{v}
}

func (x *ContinueLoginResponse) SetAuthSuccess(v *session.AuthSuccess) {
	if v == nil {
		x.xxx_hidden_Result = nil
		return
	}
	x.xxx_hidden_Result = &continueLoginResponse_AuthSuccess{v}
}

func (x *ContinueLoginResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *ContinueLoginResponse) HasChallengeRequired() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Result.(*continueLoginResponse_ChallengeRequired)
	return ok
}

func (x *ContinueLoginResponse) HasAuthSuccess() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Result.(*continueLoginResponse_AuthSuccess)
	return ok
}

func (x *ContinueLoginResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

func (x *ContinueLoginResponse) ClearChallengeRequired() {
	if _, ok := x.xxx_hidden_Result.(*continueLoginResponse_ChallengeRequired); ok {
		x.xxx_hidden_Result = nil
	}
}

func (x *ContinueLoginResponse) ClearAuthSuccess() {
	if _, ok := x.xxx_hidden_Result.(*continueLoginResponse_AuthSuccess); ok {
		x.xxx_hidden_Result = nil
	}
}

const ContinueLoginResponse_Result_not_set_case case_ContinueLoginResponse_Result = 0
const ContinueLoginResponse_ChallengeRequired_case case_ContinueLoginResponse_Result = 3
const ContinueLoginResponse_AuthSuccess_case case_ContinueLoginResponse_Result = 4

func (x *ContinueLoginResponse) WhichResult() case_ContinueLoginResponse_Result {
	if x == nil {
		return ContinueLoginResponse_Result_not_set_case
	}
	switch x.xxx_hidden_Result.(type) {
	case *continueLoginResponse_ChallengeRequired:
		return ContinueLoginResponse_ChallengeRequired_case
	case *continueLoginResponse_AuthSuccess:
		return ContinueLoginResponse_AuthSuccess_case
	default:
		return ContinueLoginResponse_Result_not_set_case
	}
}

type ContinueLoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TransitionId string
	Status       basic.AuthStatus
	// Fields of oneof xxx_hidden_Result:
	ChallengeRequired *session.ChallengeRequired
	AuthSuccess       *session.AuthSuccess
	// -- end of xxx_hidden_Result
}

func (b0 ContinueLoginResponse_builder) Build() *ContinueLoginResponse {
	m0 := &ContinueLoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TransitionId = b.TransitionId
	x.xxx_hidden_Status = b.Status
	if b.ChallengeRequired != nil {
		x.xxx_hidden_Result = &continueLoginResponse_ChallengeRequired{b.ChallengeRequired}
	}
	if b.AuthSuccess != nil {
		x.xxx_hidden_Result = &continueLoginResponse_AuthSuccess{b.AuthSuccess}
	}
	return m0
}

type case_ContinueLoginResponse_Result protoreflect.FieldNumber

func (x case_ContinueLoginResponse_Result) String() string {
	md := file_authn_v1_authentication_flow_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isContinueLoginResponse_Result interface {
	isContinueLoginResponse_Result()
}

type continueLoginResponse_ChallengeRequired struct {
	ChallengeRequired *session.ChallengeRequired `protobuf:"bytes,3,opt,name=challenge_required,json=challengeRequired,proto3,oneof"`
}

type continueLoginResponse_AuthSuccess struct {
	AuthSuccess *session.AuthSuccess `protobuf:"bytes,4,opt,name=auth_success,json=authSuccess,proto3,oneof"` // field 5 (auth_failure) removed: failures are now gRPC errors with AuthFailure as error detail
}

func (*continueLoginResponse_ChallengeRequired) isContinueLoginResponse_Result() {}

func (*continueLoginResponse_AuthSuccess) isContinueLoginResponse_Result() {}

var File_authn_v1_authentication_flow_proto protoreflect.FileDescriptor

const file_authn_v1_authentication_flow_proto_rawDesc = "" +
	"\n" +
	"\"authn/v1/authentication_flow.proto\x12\rmuid.authn.v1\x1a\x14authn/v1/basic.proto\x1a\x18authn/v1/challenge.proto\x1a\x14authn/v1/proof.proto\x1a\x16authn/v1/session.proto\x1a\x1bbuf/validate/validate.proto\"\xaf\x01\n" +
	"\x11StartLoginRequest\x127\n" +
	"\x06method\x18\x01 \x01(\x0e2\x1f.muid.authn.v1.basic.AuthMethodR\x06method\x12(\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\n" +
	"identifier\x127\n" +
	"\x06intent\x18\x03 \x01(\x0e2\x1f.muid.authn.v1.basic.AuthIntentR\x06intent\"\x89\x01\n" +
	"\x12StartLoginResponse\x12-\n" +
	"\rtransition_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ftransitionId\x12D\n" +
	"\tchallenge\x18\x02 \x01(\v2&.muid.authn.v1.challenge.AuthChallengeR\tchallenge\"{\n" +
	"\x14ContinueLoginRequest\x12-\n" +
	"\rtransition_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ftransitionId\x124\n" +
	"\x05proof\x18\x02 \x01(\v2\x1e.muid.authn.v1.proof.AuthProofR\x05proof\"\xad\x02\n" +
	"\x15ContinueLoginResponse\x12-\n" +
	"\rtransition_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ftransitionId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.muid.authn.v1.basic.AuthStatusR\x06status\x12Y\n" +
	"\x12challenge_required\x18\x03 \x01(\v2(.muid.authn.v1.session.ChallengeRequiredH\x00R\x11challengeRequired\x12G\n" +
	"\fauth_success\x18\x04 \x01(\v2\".muid.authn.v1.session.AuthSuccessH\x00R\vauthSuccessB\b\n" +
	"\x06result2\xca\x01\n" +
	"\x19AuthenticationFlowService\x12Q\n" +
	"\n" +
	"StartLogin\x12 .muid.authn.v1.StartLoginRequest\x1a!.muid.authn.v1.StartLoginResponse\x12Z\n" +
	"\rContinueLogin\x12#.muid.authn.v1.ContinueLoginRequest\x1a$.muid.authn.v1.ContinueLoginResponseB\xaa\x01\n" +
	"\x11com.muid.authn.v1B\x17AuthenticationFlowProtoP\x01Z&sanzi.io/muid/api/proto/authn/v1;authn\xa2\x02\x03MAX\xaa\x02\rMuid.Authn.V1\xca\x02\rMuid\\Authn\\V1\xe2\x02\x19Muid\\Authn\\V1\\GPBMetadata\xea\x02\x0fMuid::Authn::V1b\x06proto3"

var file_authn_v1_authentication_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_authn_v1_authentication_flow_proto_goTypes = []any{
	(*StartLoginRequest)(nil),         // 0: muid.authn.v1.StartLoginRequest
	(*StartLoginResponse)(nil),        // 1: muid.authn.v1.StartLoginResponse
	(*ContinueLoginRequest)(nil),      // 2: muid.authn.v1.ContinueLoginRequest
	(*ContinueLoginResponse)(nil),     // 3: muid.authn.v1.ContinueLoginResponse
	(basic.AuthMethod)(0),             // 4: muid.authn.v1.basic.AuthMethod
	(basic.AuthIntent)(0),             // 5: muid.authn.v1.basic.AuthIntent
	(*challenge.AuthChallenge)(nil),   // 6: muid.authn.v1.challenge.AuthChallenge
	(*proof.AuthProof)(nil),           // 7: muid.authn.v1.proof.AuthProof
	(basic.AuthStatus)(0),             // 8: muid.authn.v1.basic.AuthStatus
	(*session.ChallengeRequired)(nil), // 9: muid.authn.v1.session.ChallengeRequired
	(*session.AuthSuccess)(nil),       // 10: muid.authn.v1.session.AuthSuccess
}
var file_authn_v1_authentication_flow_proto_depIdxs = []int32{
	4,  // 0: muid.authn.v1.StartLoginRequest.method:type_name -> muid.authn.v1.basic.AuthMethod
	5,  // 1: muid.authn.v1.StartLoginRequest.intent:type_name -> muid.authn.v1.basic.AuthIntent
	6,  // 2: muid.authn.v1.StartLoginResponse.challenge:type_name -> muid.authn.v1.challenge.AuthChallenge
	7,  // 3: muid.authn.v1.ContinueLoginRequest.proof:type_name -> muid.authn.v1.proof.AuthProof
	8,  // 4: muid.authn.v1.ContinueLoginResponse.status:type_name -> muid.authn.v1.basic.AuthStatus
	9,  // 5: muid.authn.v1.ContinueLoginResponse.challenge_required:type_name -> muid.authn.v1.session.ChallengeRequired
	10, // 6: muid.authn.v1.ContinueLoginResponse.auth_success:type_name -> muid.authn.v1.session.AuthSuccess
	0,  // 7: muid.authn.v1.AuthenticationFlowService.StartLogin:input_type -> muid.authn.v1.StartLoginRequest
	2,  // 8: muid.authn.v1.AuthenticationFlowService.ContinueLogin:input_type -> muid.authn.v1.ContinueLoginRequest
	1,  // 9: muid.authn.v1.AuthenticationFlowService.StartLogin:output_type -> muid.authn.v1.StartLoginResponse
	3,  // 10: muid.authn.v1.AuthenticationFlowService.ContinueLogin:output_type -> muid.authn.v1.ContinueLoginResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_authn_v1_authentication_flow_proto_init() }
func file_authn_v1_authentication_flow_proto_init() {
	if File_authn_v1_authentication_flow_proto != nil {
		return
	}
	file_authn_v1_authentication_flow_proto_msgTypes[3].OneofWrappers = []any{
		(*continueLoginResponse_ChallengeRequired)(nil),
		(*continueLoginResponse_AuthSuccess)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authn_v1_authentication_flow_proto_rawDesc), len(file_authn_v1_authentication_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authn_v1_authentication_flow_proto_goTypes,
		DependencyIndexes: file_authn_v1_authentication_flow_proto_depIdxs,
		MessageInfos:      file_authn_v1_authentication_flow_proto_msgTypes,
	}.Build()
	File_authn_v1_authentication_flow_proto = out.File
	file_authn_v1_authentication_flow_proto_goTypes = nil
	file_authn_v1_authentication_flow_proto_depIdxs = nil
}
