syntax = "proto3";

package muid.authn.v1;

import "v1/basic.proto";
import "v1/certification.proto";
import "v1/challenge.proto";
import "v1/client.proto";
import "v1/proof.proto";
import "v1/session.proto";

option go_package = "sanzi.io/muid/api/proto/authn/v1;authn";

service AuthnService {
  /// authentication APIs
  rpc StartAuthSession(StartAuthSessionRequest) returns (StartAuthSessionResponse);
  rpc ContinueAuthSession(ContinueAuthSessionRequest) returns (ContinueAuthSessionResponse);

  /// infrastructure APIs
  rpc GetPublicKeys(GetPublicKeysRequest) returns (GetPublicKeysResponse);

  /// user related APIs, for user to manage their sessions.
  rpc RevokeFederatedIdentity(RevokeFederatedIdentityRequest) returns (RevokeFederatedIdentityResponse);
  rpc GetAuthorizedSession(GetSessionRequest) returns (GetSessionResponse);

  // user session management APIs
  rpc RevokeSession(RevokeSessionRequest) returns (RevokeSessionResponse);

  /// oidc token management APIs
  // user consent
  rpc OIDCListGrantedConsents(OIDCListGrantedConsentsRequest) returns (OIDCListGrantedConsentsResponse);
  rpc OIDCGrantConsent(OIDCGrantConsentRequest) returns (OIDCGrantConsentResponse);
  rpc OIDCRevokeConsent(OIDCRevokeConsentRequest) returns (OIDCRevokeConsentResponse);

  // token management
  rpc OIDCIntrospectToken(OIDCIntrospectTokenRequest) returns (OIDCIntrospectTokenResponse);
  rpc OIDCRevokeRefreshToken(OIDCRevokeRefreshTokenRequest) returns (OIDCRevokeRefreshTokenResponse);
  rpc OIDCRotateAndGetAccessToken(OIDCRotateAndGetAccessTokenRequest) returns (OIDCRotateAndGetAccessTokenResponse);
}

message StartAuthSessionRequest {
  muid.authn.v1.basic.AuthMethod method     = 1;
  string                         identifier = 2;
}

message StartAuthSessionResponse {
  string                                transition_id = 1;
  muid.authn.v1.challenge.AuthChallenge challenge     = 2;
}

message ContinueAuthSessionRequest {
  string                        transition_id = 1;
  muid.authn.v1.proof.AuthProof proof         = 2;
}

message ContinueAuthSessionResponse {
  string                         transition_id = 1;
  muid.authn.v1.basic.AuthStatus status        = 2;

  oneof result {
    muid.authn.v1.session.ChallengeRequired challenge_required = 3;
    muid.authn.v1.session.AuthSuccess       auth_success       = 4;
    muid.authn.v1.session.AuthFailure       auth_failure       = 5;
  }
}

message GetPublicKeysRequest {}

message GetPublicKeysResponse {
  repeated muid.authn.v1.certification.PublicKey public_keys = 1;
}

message GetSessionRequest {
  string session_token = 1;
}

message GetSessionResponse {
  bool                                      valid   = 1;
  muid.authn.v1.session.AuthenticatedResult session = 2;
}

message RevokeFederatedIdentityRequest {
  string session_token = 1;
  string provider      = 2;
}

message RevokeFederatedIdentityResponse {
  bool success = 1;
}

message OIDCIntrospectTokenRequest {
  string          token = 1;
  optional string hint  = 2;
}

message OIDCIntrospectTokenResponse {
  bool   active    = 1;
  string user_id   = 2;
  string client_id = 3;
  string type      = 4;

  optional string audience = 5;
  repeated string scopes   = 6;

  int64 created_at = 7;
  int64 expires_at = 8;
}

message OIDCGrantConsentRequest {
  string          session_token = 1;
  string          client_id     = 2;
  repeated string scopes        = 3;
}

message OIDCGrantConsentResponse {
  bool success = 1;
}

message OIDCRevokeConsentRequest {
  string session_token = 1;
  string client_id     = 2;
}

message OIDCRevokeConsentResponse {
  bool success = 1;
}

message OIDCListGrantedConsentsRequest {
  string session_token = 1;
}

message OIDCListGrantedConsentsResponse {
  repeated muid.authn.v1.client.AuthorizedClient clients = 1;
}

message RevokeSessionRequest {
  string session_token = 1;
}

message RevokeSessionResponse {
  bool success = 1;
}

message OIDCRevokeRefreshTokenRequest {
  string refresh_token = 1;
}

message OIDCRevokeRefreshTokenResponse {
  bool success = 1;
}

message OIDCRotateAndGetAccessTokenRequest {
  string refresh_token = 1;
}

message OIDCRotateAndGetAccessTokenResponse {
  string access_token  = 1;
  string refresh_token = 2;
  int32  expires_at    = 3;
}
