syntax = "proto3";

package muid.authn.v1.challenge;
import "buf/validate/validate.proto";

option go_package = "sanzi.io/muid/api/proto/authn/v1/challenge;challenge";

message AuthChallenge {
  string challenge_id = 1 [(buf.validate.field).string.uuid = true];

  int64 issued_at  = 2;
  int64 expires_at = 3;

  oneof challenge {
    EmailChallenge   email_challenge   = 4;
    OAuthChallenge   oauth_challenge   = 5;
    PasskeyChallenge passkey_challenge = 6;
  }
}

message EmailChallenge {
  string email_masked           = 1 [(buf.validate.field).string.max_len = 256];
  int64  resend_cooldown_millis = 2;
}

message OAuthChallenge {
  string provider = 1 [(buf.validate.field).string.max_len = 16];
  string auth_url = 2  [(buf.validate.field).string.uri = true];
}

message PasskeyChallenge {
  string state                                      = 1;
  string public_key_credential_request_options_json = 2;
  int64  timeout_millis                             = 3;
}