syntax = "proto3";

package muid.authn.v1;

import "authn/v1/session.proto";
import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "sanzi.io/muid/api/proto/authn/v1;authn";

service SessionService {
  rpc GetSessionPrincipal(GetSessionPrincipalRequest) returns (GetSessionPrincipalResponse);
  rpc RefreshSession(RefreshSessionRequest) returns (RefreshSessionResponse);
  rpc RevokeSession(RevokeSessionRequest) returns (RevokeSessionResponse);
  rpc IssueAccessToken(IssueAccessTokenRequest) returns (IssueAccessTokenResponse);
}

message SessionPrincipal {
  string user_id = 1 [(buf.validate.field).string.uuid = true];
  muid.authn.v1.session.AuthLevel auth_level = 2;
  google.protobuf.Timestamp issued_at = 3;
  google.protobuf.Timestamp expires_at = 4;
}

// Session token is passed via the authorization metadata header: "Session <token>".
message GetSessionPrincipalRequest {}

message GetSessionPrincipalResponse {
  bool valid = 1;
  SessionPrincipal principal = 2;
}

// Session token is passed via the authorization metadata header: "Session <token>".
message RevokeSessionRequest {}

message RevokeSessionResponse {
  bool success = 1;
}

// Session token is passed via the authorization metadata header: "Session <token>".
message RefreshSessionRequest {}

message RefreshSessionResponse {
  muid.authn.v1.session.SessionContext session_context = 1;
}

// Session token is passed via the authorization metadata header: "Session <token>".
message IssueAccessTokenRequest {}

message IssueAccessTokenResponse {
  muid.authn.v1.session.AccessToken access_token = 1;
}
