syntax = "proto3";

package muid.authn.v1.session;

import "v1/challenge.proto";

option go_package = "sanzi.io/muid/api/proto/authn/v1/session;session";

enum AuthLevel {
  AUTH_LEVEL_UNSPECIFIED = 0;
  AUTH_LEVEL_LOW         = 1;
  AUTH_LEVEL_MEDIUM      = 2;
  AUTH_LEVEL_HIGH        = 3;
}

message SessionContext {
  string session_id = 1;

  int64 issued_at  = 2;
  int64 expires_at = 3;
}

message AuthenticatedResult {
  string user_id = 1;

  SessionContext session_context = 2;
  AuthLevel      auth_level      = 3;
}

message ChallengeRequired {
  muid.authn.v1.challenge.AuthChallenge challenge = 1;
}

message AuthSuccess {
  AuthenticatedResult result = 1;
}

message AuthFailure {
  string reason     = 1;
  string error_code = 2;
}