// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event/v1/profile.proto

package profileevent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	claims "sanzi.io/muid/api/proto/shared/v1/claims"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProfileChangedEvent is published on NATS topic profile.change (see pkg/shared/topics).
//
// changed_fields uses proto snake_case names and each path is a single top-level segment
// relative to muid.profile.v1.GetProfileResponse (e.g. "display_name", "avatar_url").
// This matches UpdateProfile semantics: an update_mask entry such as "identity.email" or
// "identity.name" is reported here as path "email" or "display_name" respectively.
type ProfileChangedEvent struct {
	state                    protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_UserId        string                      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_ChangedFields *fieldmaskpb.FieldMask      `protobuf:"bytes,2,opt,name=changed_fields,json=changedFields,proto3"`
	xxx_hidden_Changes       *claims.IdentityInformation `protobuf:"bytes,3,opt,name=changes,proto3"`
	xxx_hidden_OccurredAt    *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ProfileChangedEvent) Reset() {
	*x = ProfileChangedEvent{}
	mi := &file_event_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileChangedEvent) ProtoMessage() {}

func (x *ProfileChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileChangedEvent) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *ProfileChangedEvent) GetChangedFields() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.xxx_hidden_ChangedFields
	}
	return nil
}

func (x *ProfileChangedEvent) GetChanges() *claims.IdentityInformation {
	if x != nil {
		return x.xxx_hidden_Changes
	}
	return nil
}

func (x *ProfileChangedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_OccurredAt
	}
	return nil
}

func (x *ProfileChangedEvent) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *ProfileChangedEvent) SetChangedFields(v *fieldmaskpb.FieldMask) {
	x.xxx_hidden_ChangedFields = v
}

func (x *ProfileChangedEvent) SetChanges(v *claims.IdentityInformation) {
	x.xxx_hidden_Changes = v
}

func (x *ProfileChangedEvent) SetOccurredAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_OccurredAt = v
}

func (x *ProfileChangedEvent) HasChangedFields() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ChangedFields != nil
}

func (x *ProfileChangedEvent) HasChanges() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Changes != nil
}

func (x *ProfileChangedEvent) HasOccurredAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OccurredAt != nil
}

func (x *ProfileChangedEvent) ClearChangedFields() {
	x.xxx_hidden_ChangedFields = nil
}

func (x *ProfileChangedEvent) ClearChanges() {
	x.xxx_hidden_Changes = nil
}

func (x *ProfileChangedEvent) ClearOccurredAt() {
	x.xxx_hidden_OccurredAt = nil
}

type ProfileChangedEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId        string
	ChangedFields *fieldmaskpb.FieldMask
	Changes       *claims.IdentityInformation
	OccurredAt    *timestamppb.Timestamp
}

func (b0 ProfileChangedEvent_builder) Build() *ProfileChangedEvent {
	m0 := &ProfileChangedEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_ChangedFields = b.ChangedFields
	x.xxx_hidden_Changes = b.Changes
	x.xxx_hidden_OccurredAt = b.OccurredAt
	return m0
}

var File_event_v1_profile_proto protoreflect.FileDescriptor

const file_event_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x16event/v1/profile.proto\x12\x15muid.event.v1.profile\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16shared/v1/claims.proto\"\xf4\x01\n" +
	"\x13ProfileChangedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12A\n" +
	"\x0echanged_fields\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\rchangedFields\x12D\n" +
	"\achanges\x18\x03 \x01(\v2*.muid.shared.v1.claims.IdentityInformationR\achanges\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAtB\xd8\x01\n" +
	"\x19com.muid.event.v1.profileB\fProfileProtoP\x01Z5sanzi.io/muid/api/proto/event/v1/profile;profileevent\xa2\x02\x04MEVP\xaa\x02\x15Muid.Event.V1.Profile\xca\x02\x15Muid\\Event\\V1\\Profile\xe2\x02!Muid\\Event\\V1\\Profile\\GPBMetadata\xea\x02\x18Muid::Event::V1::Profileb\x06proto3"

var file_event_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_v1_profile_proto_goTypes = []any{
	(*ProfileChangedEvent)(nil),        // 0: muid.event.v1.profile.ProfileChangedEvent
	(*fieldmaskpb.FieldMask)(nil),      // 1: google.protobuf.FieldMask
	(*claims.IdentityInformation)(nil), // 2: muid.shared.v1.claims.IdentityInformation
	(*timestamppb.Timestamp)(nil),      // 3: google.protobuf.Timestamp
}
var file_event_v1_profile_proto_depIdxs = []int32{
	1, // 0: muid.event.v1.profile.ProfileChangedEvent.changed_fields:type_name -> google.protobuf.FieldMask
	2, // 1: muid.event.v1.profile.ProfileChangedEvent.changes:type_name -> muid.shared.v1.claims.IdentityInformation
	3, // 2: muid.event.v1.profile.ProfileChangedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_event_v1_profile_proto_init() }
func file_event_v1_profile_proto_init() {
	if File_event_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_v1_profile_proto_rawDesc), len(file_event_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_v1_profile_proto_goTypes,
		DependencyIndexes: file_event_v1_profile_proto_depIdxs,
		MessageInfos:      file_event_v1_profile_proto_msgTypes,
	}.Build()
	File_event_v1_profile_proto = out.File
	file_event_v1_profile_proto_goTypes = nil
	file_event_v1_profile_proto_depIdxs = nil
}
