version: "3.9"

services:
    mailer:
        image: ghcr.io/Muisnow-Devs/muid:latest
        command: ["/mailer"]
        restart: always

    pubsub_bridge:
        image: ghcr.io/Muisnow-Devs/muid:latest
        command: ["/pubsub_bridge"]
        restart: always

    authn:
        image: ghcr.io/Muisnow-Devs/muid:latest
        command: ["/muid-authn"]
        restart: always

    authz:
        image: ghcr.io/Muisnow-Devs/muid:latest
        command: ["/muid-authz"]
        restart: always

    profile:
        image: ghcr.io/Muisnow-Devs/muid:latest
        command: ["/muid-profile"]
        restart: always

    gateway:
        image: ghcr.io/Muisnow-Devs/muid:latest
        command: ["/muid-gateway"]
        ports:
            - "8080:8080"
        depends_on:
            - authn
            - authz
            - profile
        restart: always
        environment:
            - GATEWAY_PORT=8080
            - GATEWAY_AUTHN_GRPC_URL=authn:8080
            - GATEWAY_AUTHZ_GRPC_URL=authz:8080
