// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: authz/v1/user.proto

package authz

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthzUserService_ListMyOrganizations_FullMethodName = "/muid.authz.v1.AuthzUserService/ListMyOrganizations"
	AuthzUserService_ListMyPermissions_FullMethodName   = "/muid.authz.v1.AuthzUserService/ListMyPermissions"
	AuthzUserService_CheckMyPermission_FullMethodName   = "/muid.authz.v1.AuthzUserService/CheckMyPermission"
)

// AuthzUserServiceClient is the client API for AuthzUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthzUserService is the default end-user surface, served on the public
// listener behind the gateway. The gateway verifies the caller's
// access/session token and injects the resolved user id as "x-user-id" gRPC
// metadata; requests therefore carry no user_id field, and authz rejects
// calls without the metadata.
type AuthzUserServiceClient interface {
	ListMyOrganizations(ctx context.Context, in *ListMyOrganizationsRequest, opts ...grpc.CallOption) (*ListMyOrganizationsResponse, error)
	ListMyPermissions(ctx context.Context, in *ListMyPermissionsRequest, opts ...grpc.CallOption) (*ListMyPermissionsResponse, error)
	CheckMyPermission(ctx context.Context, in *CheckMyPermissionRequest, opts ...grpc.CallOption) (*CheckMyPermissionResponse, error)
}

type authzUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthzUserServiceClient(cc grpc.ClientConnInterface) AuthzUserServiceClient {
	return &authzUserServiceClient{cc}
}

func (c *authzUserServiceClient) ListMyOrganizations(ctx context.Context, in *ListMyOrganizationsRequest, opts ...grpc.CallOption) (*ListMyOrganizationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyOrganizationsResponse)
	err := c.cc.Invoke(ctx, AuthzUserService_ListMyOrganizations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzUserServiceClient) ListMyPermissions(ctx context.Context, in *ListMyPermissionsRequest, opts ...grpc.CallOption) (*ListMyPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyPermissionsResponse)
	err := c.cc.Invoke(ctx, AuthzUserService_ListMyPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzUserServiceClient) CheckMyPermission(ctx context.Context, in *CheckMyPermissionRequest, opts ...grpc.CallOption) (*CheckMyPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMyPermissionResponse)
	err := c.cc.Invoke(ctx, AuthzUserService_CheckMyPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthzUserServiceServer is the server API for AuthzUserService service.
// All implementations must embed UnimplementedAuthzUserServiceServer
// for forward compatibility.
//
// AuthzUserService is the default end-user surface, served on the public
// listener behind the gateway. The gateway verifies the caller's
// access/session token and injects the resolved user id as "x-user-id" gRPC
// metadata; requests therefore carry no user_id field, and authz rejects
// calls without the metadata.
type AuthzUserServiceServer interface {
	ListMyOrganizations(context.Context, *ListMyOrganizationsRequest) (*ListMyOrganizationsResponse, error)
	ListMyPermissions(context.Context, *ListMyPermissionsRequest) (*ListMyPermissionsResponse, error)
	CheckMyPermission(context.Context, *CheckMyPermissionRequest) (*CheckMyPermissionResponse, error)
	mustEmbedUnimplementedAuthzUserServiceServer()
}

// UnimplementedAuthzUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthzUserServiceServer struct{}

func (UnimplementedAuthzUserServiceServer) ListMyOrganizations(context.Context, *ListMyOrganizationsRequest) (*ListMyOrganizationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyOrganizations not implemented")
}
func (UnimplementedAuthzUserServiceServer) ListMyPermissions(context.Context, *ListMyPermissionsRequest) (*ListMyPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyPermissions not implemented")
}
func (UnimplementedAuthzUserServiceServer) CheckMyPermission(context.Context, *CheckMyPermissionRequest) (*CheckMyPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckMyPermission not implemented")
}
func (UnimplementedAuthzUserServiceServer) mustEmbedUnimplementedAuthzUserServiceServer() {}
func (UnimplementedAuthzUserServiceServer) testEmbeddedByValue()                          {}

// UnsafeAuthzUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthzUserServiceServer will
// result in compilation errors.
type UnsafeAuthzUserServiceServer interface {
	mustEmbedUnimplementedAuthzUserServiceServer()
}

func RegisterAuthzUserServiceServer(s grpc.ServiceRegistrar, srv AuthzUserServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthzUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthzUserService_ServiceDesc, srv)
}

func _AuthzUserService_ListMyOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyOrganizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzUserServiceServer).ListMyOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzUserService_ListMyOrganizations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzUserServiceServer).ListMyOrganizations(ctx, req.(*ListMyOrganizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzUserService_ListMyPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzUserServiceServer).ListMyPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzUserService_ListMyPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzUserServiceServer).ListMyPermissions(ctx, req.(*ListMyPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzUserService_CheckMyPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMyPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzUserServiceServer).CheckMyPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzUserService_CheckMyPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzUserServiceServer).CheckMyPermission(ctx, req.(*CheckMyPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthzUserService_ServiceDesc is the grpc.ServiceDesc for AuthzUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthzUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muid.authz.v1.AuthzUserService",
	HandlerType: (*AuthzUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMyOrganizations",
			Handler:    _AuthzUserService_ListMyOrganizations_Handler,
		},
		{
			MethodName: "ListMyPermissions",
			Handler:    _AuthzUserService_ListMyPermissions_Handler,
		},
		{
			MethodName: "CheckMyPermission",
			Handler:    _AuthzUserService_CheckMyPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authz/v1/user.proto",
}
