// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"sanzi.io/muid/internal/authz/ent/oidcclient"
	"sanzi.io/muid/internal/authz/ent/oidcclientsecret"
)

// OIDCClientSecret is the model entity for the OIDCClientSecret schema.
type OIDCClientSecret struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ClientRefID holds the value of the "client_ref_id" field.
	ClientRefID uuid.UUID `json:"client_ref_id,omitempty"`
	// SecretHash holds the value of the "secret_hash" field.
	SecretHash []byte `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt time.Time `json:"revoked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OIDCClientSecretQuery when eager-loading is set.
	Edges        OIDCClientSecretEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OIDCClientSecretEdges holds the relations/edges for other nodes in the graph.
type OIDCClientSecretEdges struct {
	// Client holds the value of the client edge.
	Client *OIDCClient `json:"client,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OIDCClientSecretEdges) ClientOrErr() (*OIDCClient, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: oidcclient.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OIDCClientSecret) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oidcclientsecret.FieldSecretHash:
			values[i] = new([]byte)
		case oidcclientsecret.FieldCreatedAt, oidcclientsecret.FieldExpiresAt, oidcclientsecret.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		case oidcclientsecret.FieldID, oidcclientsecret.FieldClientRefID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OIDCClientSecret fields.
func (_m *OIDCClientSecret) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oidcclientsecret.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case oidcclientsecret.FieldClientRefID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_ref_id", values[i])
			} else if value != nil {
				_m.ClientRefID = *value
			}
		case oidcclientsecret.FieldSecretHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secret_hash", values[i])
			} else if value != nil {
				_m.SecretHash = *value
			}
		case oidcclientsecret.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oidcclientsecret.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case oidcclientsecret.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OIDCClientSecret.
// This includes values selected through modifiers, order, etc.
func (_m *OIDCClientSecret) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClient queries the "client" edge of the OIDCClientSecret entity.
func (_m *OIDCClientSecret) QueryClient() *OIDCClientQuery {
	return NewOIDCClientSecretClient(_m.config).QueryClient(_m)
}

// Update returns a builder for updating this OIDCClientSecret.
// Note that you need to call OIDCClientSecret.Unwrap() before calling this method if this OIDCClientSecret
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OIDCClientSecret) Update() *OIDCClientSecretUpdateOne {
	return NewOIDCClientSecretClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OIDCClientSecret entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OIDCClientSecret) Unwrap() *OIDCClientSecret {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OIDCClientSecret is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OIDCClientSecret) String() string {
	var builder strings.Builder
	builder.WriteString("OIDCClientSecret(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("client_ref_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientRefID))
	builder.WriteString(", ")
	builder.WriteString("secret_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("revoked_at=")
	builder.WriteString(_m.RevokedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OIDCClientSecrets is a parsable slice of OIDCClientSecret.
type OIDCClientSecrets []*OIDCClientSecret
