// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"sanzi.io/muid/internal/authz/ent/oidcclient"
	"sanzi.io/muid/internal/authz/ent/oidcgrant"
	"sanzi.io/muid/internal/authz/ent/userref"
)

// OIDCGrantCreate is the builder for creating a OIDCGrant entity.
type OIDCGrantCreate struct {
	config
	mutation *OIDCGrantMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *OIDCGrantCreate) SetUserID(v uuid.UUID) *OIDCGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetClientRefID sets the "client_ref_id" field.
func (_c *OIDCGrantCreate) SetClientRefID(v uuid.UUID) *OIDCGrantCreate {
	_c.mutation.SetClientRefID(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OIDCGrantCreate) SetScopes(v []string) *OIDCGrantCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *OIDCGrantCreate) SetLastUsedAt(v time.Time) *OIDCGrantCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *OIDCGrantCreate) SetNillableLastUsedAt(v *time.Time) *OIDCGrantCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *OIDCGrantCreate) SetRevokedAt(v time.Time) *OIDCGrantCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *OIDCGrantCreate) SetNillableRevokedAt(v *time.Time) *OIDCGrantCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OIDCGrantCreate) SetCreatedAt(v time.Time) *OIDCGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OIDCGrantCreate) SetNillableCreatedAt(v *time.Time) *OIDCGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OIDCGrantCreate) SetUpdatedAt(v time.Time) *OIDCGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OIDCGrantCreate) SetNillableUpdatedAt(v *time.Time) *OIDCGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAuthorizedAt sets the "authorized_at" field.
func (_c *OIDCGrantCreate) SetAuthorizedAt(v time.Time) *OIDCGrantCreate {
	_c.mutation.SetAuthorizedAt(v)
	return _c
}

// SetNillableAuthorizedAt sets the "authorized_at" field if the given value is not nil.
func (_c *OIDCGrantCreate) SetNillableAuthorizedAt(v *time.Time) *OIDCGrantCreate {
	if v != nil {
		_c.SetAuthorizedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OIDCGrantCreate) SetID(v uuid.UUID) *OIDCGrantCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OIDCGrantCreate) SetNillableID(v *uuid.UUID) *OIDCGrantCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the UserRef entity.
func (_c *OIDCGrantCreate) SetUser(v *UserRef) *OIDCGrantCreate {
	return _c.SetUserID(v.ID)
}

// SetClientID sets the "client" edge to the OIDCClient entity by ID.
func (_c *OIDCGrantCreate) SetClientID(id uuid.UUID) *OIDCGrantCreate {
	_c.mutation.SetClientID(id)
	return _c
}

// SetClient sets the "client" edge to the OIDCClient entity.
func (_c *OIDCGrantCreate) SetClient(v *OIDCClient) *OIDCGrantCreate {
	return _c.SetClientID(v.ID)
}

// Mutation returns the OIDCGrantMutation object of the builder.
func (_c *OIDCGrantCreate) Mutation() *OIDCGrantMutation {
	return _c.mutation
}

// Save creates the OIDCGrant in the database.
func (_c *OIDCGrantCreate) Save(ctx context.Context) (*OIDCGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OIDCGrantCreate) SaveX(ctx context.Context) *OIDCGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OIDCGrantCreate) defaults() {
	if _, ok := _c.mutation.Scopes(); !ok {
		v := oidcgrant.DefaultScopes
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oidcgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oidcgrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AuthorizedAt(); !ok {
		v := oidcgrant.DefaultAuthorizedAt()
		_c.mutation.SetAuthorizedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oidcgrant.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OIDCGrantCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OIDCGrant.user_id"`)}
	}
	if _, ok := _c.mutation.ClientRefID(); !ok {
		return &ValidationError{Name: "client_ref_id", err: errors.New(`ent: missing required field "OIDCGrant.client_ref_id"`)}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OIDCGrant.scopes"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OIDCGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OIDCGrant.updated_at"`)}
	}
	if _, ok := _c.mutation.AuthorizedAt(); !ok {
		return &ValidationError{Name: "authorized_at", err: errors.New(`ent: missing required field "OIDCGrant.authorized_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OIDCGrant.user"`)}
	}
	if len(_c.mutation.ClientIDs()) == 0 {
		return &ValidationError{Name: "client", err: errors.New(`ent: missing required edge "OIDCGrant.client"`)}
	}
	return nil
}

func (_c *OIDCGrantCreate) sqlSave(ctx context.Context) (*OIDCGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OIDCGrantCreate) createSpec() (*OIDCGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &OIDCGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oidcgrant.Table, sqlgraph.NewFieldSpec(oidcgrant.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oidcgrant.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(oidcgrant.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(oidcgrant.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oidcgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcgrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AuthorizedAt(); ok {
		_spec.SetField(oidcgrant.FieldAuthorizedAt, field.TypeTime, value)
		_node.AuthorizedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oidcgrant.UserTable,
			Columns: []string{oidcgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userref.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oidcgrant.ClientTable,
			Columns: []string{oidcgrant.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oidcclient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClientRefID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OIDCGrantCreateBulk is the builder for creating many OIDCGrant entities in bulk.
type OIDCGrantCreateBulk struct {
	config
	err      error
	builders []*OIDCGrantCreate
}

// Save creates the OIDCGrant entities in the database.
func (_c *OIDCGrantCreateBulk) Save(ctx context.Context) ([]*OIDCGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OIDCGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OIDCGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OIDCGrantCreateBulk) SaveX(ctx context.Context) []*OIDCGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
