// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"sanzi.io/muid/internal/authz/ent/oidccallbackurl"
	"sanzi.io/muid/internal/authz/ent/oidcclient"
)

// OIDCCallbackURL is the model entity for the OIDCCallbackURL schema.
type OIDCCallbackURL struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ClientRefID holds the value of the "client_ref_id" field.
	ClientRefID uuid.UUID `json:"client_ref_id,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OIDCCallbackURLQuery when eager-loading is set.
	Edges        OIDCCallbackURLEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OIDCCallbackURLEdges holds the relations/edges for other nodes in the graph.
type OIDCCallbackURLEdges struct {
	// Client holds the value of the client edge.
	Client *OIDCClient `json:"client,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OIDCCallbackURLEdges) ClientOrErr() (*OIDCClient, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: oidcclient.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OIDCCallbackURL) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oidccallbackurl.FieldURL:
			values[i] = new(sql.NullString)
		case oidccallbackurl.FieldCreatedAt, oidccallbackurl.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case oidccallbackurl.FieldID, oidccallbackurl.FieldClientRefID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OIDCCallbackURL fields.
func (_m *OIDCCallbackURL) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oidccallbackurl.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case oidccallbackurl.FieldClientRefID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_ref_id", values[i])
			} else if value != nil {
				_m.ClientRefID = *value
			}
		case oidccallbackurl.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case oidccallbackurl.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oidccallbackurl.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OIDCCallbackURL.
// This includes values selected through modifiers, order, etc.
func (_m *OIDCCallbackURL) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClient queries the "client" edge of the OIDCCallbackURL entity.
func (_m *OIDCCallbackURL) QueryClient() *OIDCClientQuery {
	return NewOIDCCallbackURLClient(_m.config).QueryClient(_m)
}

// Update returns a builder for updating this OIDCCallbackURL.
// Note that you need to call OIDCCallbackURL.Unwrap() before calling this method if this OIDCCallbackURL
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OIDCCallbackURL) Update() *OIDCCallbackURLUpdateOne {
	return NewOIDCCallbackURLClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OIDCCallbackURL entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OIDCCallbackURL) Unwrap() *OIDCCallbackURL {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OIDCCallbackURL is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OIDCCallbackURL) String() string {
	var builder strings.Builder
	builder.WriteString("OIDCCallbackURL(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("client_ref_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientRefID))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OIDCCallbackURLs is a parsable slice of OIDCCallbackURL.
type OIDCCallbackURLs []*OIDCCallbackURL
