// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"sanzi.io/muid/internal/authz/ent/policyrevision"
	"sanzi.io/muid/internal/authz/ent/predicate"
)

// PolicyRevisionDelete is the builder for deleting a PolicyRevision entity.
type PolicyRevisionDelete struct {
	config
	hooks    []Hook
	mutation *PolicyRevisionMutation
}

// Where appends a list predicates to the PolicyRevisionDelete builder.
func (_d *PolicyRevisionDelete) Where(ps ...predicate.PolicyRevision) *PolicyRevisionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PolicyRevisionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PolicyRevisionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PolicyRevisionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(policyrevision.Table, sqlgraph.NewFieldSpec(policyrevision.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PolicyRevisionDeleteOne is the builder for deleting a single PolicyRevision entity.
type PolicyRevisionDeleteOne struct {
	_d *PolicyRevisionDelete
}

// Where appends a list predicates to the PolicyRevisionDelete builder.
func (_d *PolicyRevisionDeleteOne) Where(ps ...predicate.PolicyRevision) *PolicyRevisionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PolicyRevisionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{policyrevision.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PolicyRevisionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
