syntax = "proto3";

package muid.shared.v1.claims;
import "buf/validate/validate.proto";

option go_package = "sanzi.io/muid/api/proto/shared/v1/claims;claims";

message IdentityClaims {
  optional string name        = 1 [(buf.validate.field).string.max_len = 32];
  optional string given_name  = 2 [(buf.validate.field).string.max_len = 64];
  optional string family_name = 3 [(buf.validate.field).string.max_len = 64];

  optional string picture = 4;
  optional string locale  = 5 [(buf.validate.field).string.len = 32];

  optional string email          = 6 [(buf.validate.field).string.email = true];
  optional bool   email_verified = 7;
}