// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserAvatarsColumns holds the columns for the "user_avatars" table.
	UserAvatarsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "object_key", Type: field.TypeString},
		{Name: "content_type", Type: field.TypeString},
		{Name: "byte_size", Type: field.TypeInt64, Default: 0},
		{Name: "public_url", Type: field.TypeString, Nullable: true},
		{Name: "uploaded_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// UserAvatarsTable holds the schema information for the "user_avatars" table.
	UserAvatarsTable = &schema.Table{
		Name:       "user_avatars",
		Columns:    UserAvatarsColumns,
		PrimaryKey: []*schema.Column{UserAvatarsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_avatars_user_profiles_avatars",
				Columns:    []*schema.Column{UserAvatarsColumns[7]},
				RefColumns: []*schema.Column{UserProfilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "useravatar_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserAvatarsColumns[7]},
			},
		},
	}
	// UserOriginalIdentitiesColumns holds the columns for the "user_original_identities" table.
	UserOriginalIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "original_identity", Type: field.TypeString, Unique: true},
		{Name: "user_original_identity_user", Type: field.TypeUUID},
	}
	// UserOriginalIdentitiesTable holds the schema information for the "user_original_identities" table.
	UserOriginalIdentitiesTable = &schema.Table{
		Name:       "user_original_identities",
		Columns:    UserOriginalIdentitiesColumns,
		PrimaryKey: []*schema.Column{UserOriginalIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_original_identities_user_profiles_user",
				Columns:    []*schema.Column{UserOriginalIdentitiesColumns[2]},
				RefColumns: []*schema.Column{UserProfilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UserProfilesColumns holds the columns for the "user_profiles" table.
	UserProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email_ref", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "locale", Type: field.TypeString, Default: "en"},
		{Name: "biography", Type: field.TypeString, Size: 1024, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_profile_original_identity", Type: field.TypeInt, Nullable: true},
	}
	// UserProfilesTable holds the schema information for the "user_profiles" table.
	UserProfilesTable = &schema.Table{
		Name:       "user_profiles",
		Columns:    UserProfilesColumns,
		PrimaryKey: []*schema.Column{UserProfilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_profiles_user_original_identities_original_identity",
				Columns:    []*schema.Column{UserProfilesColumns[8]},
				RefColumns: []*schema.Column{UserOriginalIdentitiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userprofile_email_ref",
				Unique:  false,
				Columns: []*schema.Column{UserProfilesColumns[1]},
			},
			{
				Name:    "userprofile_username",
				Unique:  false,
				Columns: []*schema.Column{UserProfilesColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserAvatarsTable,
		UserOriginalIdentitiesTable,
		UserProfilesTable,
	}
)

func init() {
	UserAvatarsTable.ForeignKeys[0].RefTable = UserProfilesTable
	UserOriginalIdentitiesTable.ForeignKeys[0].RefTable = UserProfilesTable
	UserProfilesTable.ForeignKeys[0].RefTable = UserOriginalIdentitiesTable
}
