// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// OrganizationProfile is the predicate function for organizationprofile builders.
type OrganizationProfile func(*sql.Selector)

// UserAvatar is the predicate function for useravatar builders.
type UserAvatar func(*sql.Selector)

// UserOriginalIdentity is the predicate function for useroriginalidentity builders.
type UserOriginalIdentity func(*sql.Selector)

// UserProfile is the predicate function for userprofile builders.
type UserProfile func(*sql.Selector)
