// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"sanzi.io/muid/internal/authn/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"sanzi.io/muid/internal/authn/ent/oidcrefreshtoken"
	"sanzi.io/muid/internal/authn/ent/userpasskey"
	"sanzi.io/muid/internal/authn/ent/userref"
	"sanzi.io/muid/internal/authn/ent/usersession"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// OIDCRefreshToken is the client for interacting with the OIDCRefreshToken builders.
	OIDCRefreshToken *OIDCRefreshTokenClient
	// UserPasskey is the client for interacting with the UserPasskey builders.
	UserPasskey *UserPasskeyClient
	// UserRef is the client for interacting with the UserRef builders.
	UserRef *UserRefClient
	// UserSession is the client for interacting with the UserSession builders.
	UserSession *UserSessionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.OIDCRefreshToken = NewOIDCRefreshTokenClient(c.config)
	c.UserPasskey = NewUserPasskeyClient(c.config)
	c.UserRef = NewUserRefClient(c.config)
	c.UserSession = NewUserSessionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		OIDCRefreshToken: NewOIDCRefreshTokenClient(cfg),
		UserPasskey:      NewUserPasskeyClient(cfg),
		UserRef:          NewUserRefClient(cfg),
		UserSession:      NewUserSessionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		OIDCRefreshToken: NewOIDCRefreshTokenClient(cfg),
		UserPasskey:      NewUserPasskeyClient(cfg),
		UserRef:          NewUserRefClient(cfg),
		UserSession:      NewUserSessionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		OIDCRefreshToken.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.OIDCRefreshToken.Use(hooks...)
	c.UserPasskey.Use(hooks...)
	c.UserRef.Use(hooks...)
	c.UserSession.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.OIDCRefreshToken.Intercept(interceptors...)
	c.UserPasskey.Intercept(interceptors...)
	c.UserRef.Intercept(interceptors...)
	c.UserSession.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *OIDCRefreshTokenMutation:
		return c.OIDCRefreshToken.mutate(ctx, m)
	case *UserPasskeyMutation:
		return c.UserPasskey.mutate(ctx, m)
	case *UserRefMutation:
		return c.UserRef.mutate(ctx, m)
	case *UserSessionMutation:
		return c.UserSession.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// OIDCRefreshTokenClient is a client for the OIDCRefreshToken schema.
type OIDCRefreshTokenClient struct {
	config
}

// NewOIDCRefreshTokenClient returns a client for the OIDCRefreshToken from the given config.
func NewOIDCRefreshTokenClient(c config) *OIDCRefreshTokenClient {
	return &OIDCRefreshTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oidcrefreshtoken.Hooks(f(g(h())))`.
func (c *OIDCRefreshTokenClient) Use(hooks ...Hook) {
	c.hooks.OIDCRefreshToken = append(c.hooks.OIDCRefreshToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oidcrefreshtoken.Intercept(f(g(h())))`.
func (c *OIDCRefreshTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.OIDCRefreshToken = append(c.inters.OIDCRefreshToken, interceptors...)
}

// Create returns a builder for creating a OIDCRefreshToken entity.
func (c *OIDCRefreshTokenClient) Create() *OIDCRefreshTokenCreate {
	mutation := newOIDCRefreshTokenMutation(c.config, OpCreate)
	return &OIDCRefreshTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OIDCRefreshToken entities.
func (c *OIDCRefreshTokenClient) CreateBulk(builders ...*OIDCRefreshTokenCreate) *OIDCRefreshTokenCreateBulk {
	return &OIDCRefreshTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OIDCRefreshTokenClient) MapCreateBulk(slice any, setFunc func(*OIDCRefreshTokenCreate, int)) *OIDCRefreshTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OIDCRefreshTokenCreateBulk{err: fmt.Errorf("calling to OIDCRefreshTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OIDCRefreshTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OIDCRefreshTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OIDCRefreshToken.
func (c *OIDCRefreshTokenClient) Update() *OIDCRefreshTokenUpdate {
	mutation := newOIDCRefreshTokenMutation(c.config, OpUpdate)
	return &OIDCRefreshTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OIDCRefreshTokenClient) UpdateOne(_m *OIDCRefreshToken) *OIDCRefreshTokenUpdateOne {
	mutation := newOIDCRefreshTokenMutation(c.config, OpUpdateOne, withOIDCRefreshToken(_m))
	return &OIDCRefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OIDCRefreshTokenClient) UpdateOneID(id uuid.UUID) *OIDCRefreshTokenUpdateOne {
	mutation := newOIDCRefreshTokenMutation(c.config, OpUpdateOne, withOIDCRefreshTokenID(id))
	return &OIDCRefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OIDCRefreshToken.
func (c *OIDCRefreshTokenClient) Delete() *OIDCRefreshTokenDelete {
	mutation := newOIDCRefreshTokenMutation(c.config, OpDelete)
	return &OIDCRefreshTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OIDCRefreshTokenClient) DeleteOne(_m *OIDCRefreshToken) *OIDCRefreshTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OIDCRefreshTokenClient) DeleteOneID(id uuid.UUID) *OIDCRefreshTokenDeleteOne {
	builder := c.Delete().Where(oidcrefreshtoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OIDCRefreshTokenDeleteOne{builder}
}

// Query returns a query builder for OIDCRefreshToken.
func (c *OIDCRefreshTokenClient) Query() *OIDCRefreshTokenQuery {
	return &OIDCRefreshTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOIDCRefreshToken},
		inters: c.Interceptors(),
	}
}

// Get returns a OIDCRefreshToken entity by its id.
func (c *OIDCRefreshTokenClient) Get(ctx context.Context, id uuid.UUID) (*OIDCRefreshToken, error) {
	return c.Query().Where(oidcrefreshtoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OIDCRefreshTokenClient) GetX(ctx context.Context, id uuid.UUID) *OIDCRefreshToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a OIDCRefreshToken.
func (c *OIDCRefreshTokenClient) QueryUser(_m *OIDCRefreshToken) *UserRefQuery {
	query := (&UserRefClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(oidcrefreshtoken.Table, oidcrefreshtoken.FieldID, id),
			sqlgraph.To(userref.Table, userref.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, oidcrefreshtoken.UserTable, oidcrefreshtoken.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParent queries the parent edge of a OIDCRefreshToken.
func (c *OIDCRefreshTokenClient) QueryParent(_m *OIDCRefreshToken) *OIDCRefreshTokenQuery {
	query := (&OIDCRefreshTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(oidcrefreshtoken.Table, oidcrefreshtoken.FieldID, id),
			sqlgraph.To(oidcrefreshtoken.Table, oidcrefreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, oidcrefreshtoken.ParentTable, oidcrefreshtoken.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildren queries the children edge of a OIDCRefreshToken.
func (c *OIDCRefreshTokenClient) QueryChildren(_m *OIDCRefreshToken) *OIDCRefreshTokenQuery {
	query := (&OIDCRefreshTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(oidcrefreshtoken.Table, oidcrefreshtoken.FieldID, id),
			sqlgraph.To(oidcrefreshtoken.Table, oidcrefreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, oidcrefreshtoken.ChildrenTable, oidcrefreshtoken.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OIDCRefreshTokenClient) Hooks() []Hook {
	return c.hooks.OIDCRefreshToken
}

// Interceptors returns the client interceptors.
func (c *OIDCRefreshTokenClient) Interceptors() []Interceptor {
	return c.inters.OIDCRefreshToken
}

func (c *OIDCRefreshTokenClient) mutate(ctx context.Context, m *OIDCRefreshTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OIDCRefreshTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OIDCRefreshTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OIDCRefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OIDCRefreshTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OIDCRefreshToken mutation op: %q", m.Op())
	}
}

// UserPasskeyClient is a client for the UserPasskey schema.
type UserPasskeyClient struct {
	config
}

// NewUserPasskeyClient returns a client for the UserPasskey from the given config.
func NewUserPasskeyClient(c config) *UserPasskeyClient {
	return &UserPasskeyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userpasskey.Hooks(f(g(h())))`.
func (c *UserPasskeyClient) Use(hooks ...Hook) {
	c.hooks.UserPasskey = append(c.hooks.UserPasskey, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userpasskey.Intercept(f(g(h())))`.
func (c *UserPasskeyClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserPasskey = append(c.inters.UserPasskey, interceptors...)
}

// Create returns a builder for creating a UserPasskey entity.
func (c *UserPasskeyClient) Create() *UserPasskeyCreate {
	mutation := newUserPasskeyMutation(c.config, OpCreate)
	return &UserPasskeyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserPasskey entities.
func (c *UserPasskeyClient) CreateBulk(builders ...*UserPasskeyCreate) *UserPasskeyCreateBulk {
	return &UserPasskeyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserPasskeyClient) MapCreateBulk(slice any, setFunc func(*UserPasskeyCreate, int)) *UserPasskeyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserPasskeyCreateBulk{err: fmt.Errorf("calling to UserPasskeyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserPasskeyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserPasskeyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserPasskey.
func (c *UserPasskeyClient) Update() *UserPasskeyUpdate {
	mutation := newUserPasskeyMutation(c.config, OpUpdate)
	return &UserPasskeyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserPasskeyClient) UpdateOne(_m *UserPasskey) *UserPasskeyUpdateOne {
	mutation := newUserPasskeyMutation(c.config, OpUpdateOne, withUserPasskey(_m))
	return &UserPasskeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserPasskeyClient) UpdateOneID(id uuid.UUID) *UserPasskeyUpdateOne {
	mutation := newUserPasskeyMutation(c.config, OpUpdateOne, withUserPasskeyID(id))
	return &UserPasskeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserPasskey.
func (c *UserPasskeyClient) Delete() *UserPasskeyDelete {
	mutation := newUserPasskeyMutation(c.config, OpDelete)
	return &UserPasskeyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserPasskeyClient) DeleteOne(_m *UserPasskey) *UserPasskeyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserPasskeyClient) DeleteOneID(id uuid.UUID) *UserPasskeyDeleteOne {
	builder := c.Delete().Where(userpasskey.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserPasskeyDeleteOne{builder}
}

// Query returns a query builder for UserPasskey.
func (c *UserPasskeyClient) Query() *UserPasskeyQuery {
	return &UserPasskeyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserPasskey},
		inters: c.Interceptors(),
	}
}

// Get returns a UserPasskey entity by its id.
func (c *UserPasskeyClient) Get(ctx context.Context, id uuid.UUID) (*UserPasskey, error) {
	return c.Query().Where(userpasskey.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserPasskeyClient) GetX(ctx context.Context, id uuid.UUID) *UserPasskey {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UserPasskey.
func (c *UserPasskeyClient) QueryUser(_m *UserPasskey) *UserRefQuery {
	query := (&UserRefClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(userpasskey.Table, userpasskey.FieldID, id),
			sqlgraph.To(userref.Table, userref.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userpasskey.UserTable, userpasskey.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserPasskeyClient) Hooks() []Hook {
	return c.hooks.UserPasskey
}

// Interceptors returns the client interceptors.
func (c *UserPasskeyClient) Interceptors() []Interceptor {
	return c.inters.UserPasskey
}

func (c *UserPasskeyClient) mutate(ctx context.Context, m *UserPasskeyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserPasskeyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserPasskeyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserPasskeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserPasskeyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserPasskey mutation op: %q", m.Op())
	}
}

// UserRefClient is a client for the UserRef schema.
type UserRefClient struct {
	config
}

// NewUserRefClient returns a client for the UserRef from the given config.
func NewUserRefClient(c config) *UserRefClient {
	return &UserRefClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userref.Hooks(f(g(h())))`.
func (c *UserRefClient) Use(hooks ...Hook) {
	c.hooks.UserRef = append(c.hooks.UserRef, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userref.Intercept(f(g(h())))`.
func (c *UserRefClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserRef = append(c.inters.UserRef, interceptors...)
}

// Create returns a builder for creating a UserRef entity.
func (c *UserRefClient) Create() *UserRefCreate {
	mutation := newUserRefMutation(c.config, OpCreate)
	return &UserRefCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserRef entities.
func (c *UserRefClient) CreateBulk(builders ...*UserRefCreate) *UserRefCreateBulk {
	return &UserRefCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserRefClient) MapCreateBulk(slice any, setFunc func(*UserRefCreate, int)) *UserRefCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserRefCreateBulk{err: fmt.Errorf("calling to UserRefClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserRefCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserRefCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserRef.
func (c *UserRefClient) Update() *UserRefUpdate {
	mutation := newUserRefMutation(c.config, OpUpdate)
	return &UserRefUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserRefClient) UpdateOne(_m *UserRef) *UserRefUpdateOne {
	mutation := newUserRefMutation(c.config, OpUpdateOne, withUserRef(_m))
	return &UserRefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserRefClient) UpdateOneID(id uuid.UUID) *UserRefUpdateOne {
	mutation := newUserRefMutation(c.config, OpUpdateOne, withUserRefID(id))
	return &UserRefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserRef.
func (c *UserRefClient) Delete() *UserRefDelete {
	mutation := newUserRefMutation(c.config, OpDelete)
	return &UserRefDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserRefClient) DeleteOne(_m *UserRef) *UserRefDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserRefClient) DeleteOneID(id uuid.UUID) *UserRefDeleteOne {
	builder := c.Delete().Where(userref.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserRefDeleteOne{builder}
}

// Query returns a query builder for UserRef.
func (c *UserRefClient) Query() *UserRefQuery {
	return &UserRefQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserRef},
		inters: c.Interceptors(),
	}
}

// Get returns a UserRef entity by its id.
func (c *UserRefClient) Get(ctx context.Context, id uuid.UUID) (*UserRef, error) {
	return c.Query().Where(userref.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserRefClient) GetX(ctx context.Context, id uuid.UUID) *UserRef {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySessions queries the sessions edge of a UserRef.
func (c *UserRefClient) QuerySessions(_m *UserRef) *UserSessionQuery {
	query := (&UserSessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(userref.Table, userref.FieldID, id),
			sqlgraph.To(usersession.Table, usersession.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userref.SessionsTable, userref.SessionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPasskeys queries the passkeys edge of a UserRef.
func (c *UserRefClient) QueryPasskeys(_m *UserRef) *UserPasskeyQuery {
	query := (&UserPasskeyClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(userref.Table, userref.FieldID, id),
			sqlgraph.To(userpasskey.Table, userpasskey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userref.PasskeysTable, userref.PasskeysColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOidcRefreshTokens queries the oidc_refresh_tokens edge of a UserRef.
func (c *UserRefClient) QueryOidcRefreshTokens(_m *UserRef) *OIDCRefreshTokenQuery {
	query := (&OIDCRefreshTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(userref.Table, userref.FieldID, id),
			sqlgraph.To(oidcrefreshtoken.Table, oidcrefreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userref.OidcRefreshTokensTable, userref.OidcRefreshTokensColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserRefClient) Hooks() []Hook {
	return c.hooks.UserRef
}

// Interceptors returns the client interceptors.
func (c *UserRefClient) Interceptors() []Interceptor {
	return c.inters.UserRef
}

func (c *UserRefClient) mutate(ctx context.Context, m *UserRefMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserRefCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserRefUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserRefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserRefDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserRef mutation op: %q", m.Op())
	}
}

// UserSessionClient is a client for the UserSession schema.
type UserSessionClient struct {
	config
}

// NewUserSessionClient returns a client for the UserSession from the given config.
func NewUserSessionClient(c config) *UserSessionClient {
	return &UserSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usersession.Hooks(f(g(h())))`.
func (c *UserSessionClient) Use(hooks ...Hook) {
	c.hooks.UserSession = append(c.hooks.UserSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usersession.Intercept(f(g(h())))`.
func (c *UserSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserSession = append(c.inters.UserSession, interceptors...)
}

// Create returns a builder for creating a UserSession entity.
func (c *UserSessionClient) Create() *UserSessionCreate {
	mutation := newUserSessionMutation(c.config, OpCreate)
	return &UserSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserSession entities.
func (c *UserSessionClient) CreateBulk(builders ...*UserSessionCreate) *UserSessionCreateBulk {
	return &UserSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserSessionClient) MapCreateBulk(slice any, setFunc func(*UserSessionCreate, int)) *UserSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserSessionCreateBulk{err: fmt.Errorf("calling to UserSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserSession.
func (c *UserSessionClient) Update() *UserSessionUpdate {
	mutation := newUserSessionMutation(c.config, OpUpdate)
	return &UserSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserSessionClient) UpdateOne(_m *UserSession) *UserSessionUpdateOne {
	mutation := newUserSessionMutation(c.config, OpUpdateOne, withUserSession(_m))
	return &UserSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserSessionClient) UpdateOneID(id uuid.UUID) *UserSessionUpdateOne {
	mutation := newUserSessionMutation(c.config, OpUpdateOne, withUserSessionID(id))
	return &UserSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserSession.
func (c *UserSessionClient) Delete() *UserSessionDelete {
	mutation := newUserSessionMutation(c.config, OpDelete)
	return &UserSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserSessionClient) DeleteOne(_m *UserSession) *UserSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserSessionClient) DeleteOneID(id uuid.UUID) *UserSessionDeleteOne {
	builder := c.Delete().Where(usersession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserSessionDeleteOne{builder}
}

// Query returns a query builder for UserSession.
func (c *UserSessionClient) Query() *UserSessionQuery {
	return &UserSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserSession},
		inters: c.Interceptors(),
	}
}

// Get returns a UserSession entity by its id.
func (c *UserSessionClient) Get(ctx context.Context, id uuid.UUID) (*UserSession, error) {
	return c.Query().Where(usersession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserSessionClient) GetX(ctx context.Context, id uuid.UUID) *UserSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UserSession.
func (c *UserSessionClient) QueryUser(_m *UserSession) *UserRefQuery {
	query := (&UserRefClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usersession.Table, usersession.FieldID, id),
			sqlgraph.To(userref.Table, userref.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usersession.UserTable, usersession.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserSessionClient) Hooks() []Hook {
	return c.hooks.UserSession
}

// Interceptors returns the client interceptors.
func (c *UserSessionClient) Interceptors() []Interceptor {
	return c.inters.UserSession
}

func (c *UserSessionClient) mutate(ctx context.Context, m *UserSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserSession mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		OIDCRefreshToken, UserPasskey, UserRef, UserSession []ent.Hook
	}
	inters struct {
		OIDCRefreshToken, UserPasskey, UserRef, UserSession []ent.Interceptor
	}
)
