// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"sanzi.io/muid/internal/authn/ent/schema"
	"sanzi.io/muid/internal/authn/ent/useremail"
	"sanzi.io/muid/internal/authn/ent/userfederatedidentity"
	"sanzi.io/muid/internal/authn/ent/useridentity"
	"sanzi.io/muid/internal/authn/ent/userpasskey"
	"sanzi.io/muid/internal/authn/ent/userref"
	"sanzi.io/muid/internal/authn/ent/usersession"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	useremailFields := schema.UserEmail{}.Fields()
	_ = useremailFields
	// useremailDescEmail is the schema descriptor for email field.
	useremailDescEmail := useremailFields[3].Descriptor()
	// useremail.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	useremail.EmailValidator = useremailDescEmail.Validators[0].(func(string) error)
	// useremailDescIsPrimary is the schema descriptor for is_primary field.
	useremailDescIsPrimary := useremailFields[4].Descriptor()
	// useremail.DefaultIsPrimary holds the default value on creation for the is_primary field.
	useremail.DefaultIsPrimary = useremailDescIsPrimary.Default.(bool)
	// useremailDescCreatedAt is the schema descriptor for created_at field.
	useremailDescCreatedAt := useremailFields[5].Descriptor()
	// useremail.DefaultCreatedAt holds the default value on creation for the created_at field.
	useremail.DefaultCreatedAt = useremailDescCreatedAt.Default.(func() time.Time)
	// useremailDescUpdatedAt is the schema descriptor for updated_at field.
	useremailDescUpdatedAt := useremailFields[6].Descriptor()
	// useremail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useremail.DefaultUpdatedAt = useremailDescUpdatedAt.Default.(func() time.Time)
	// useremail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useremail.UpdateDefaultUpdatedAt = useremailDescUpdatedAt.UpdateDefault.(func() time.Time)
	userfederatedidentityFields := schema.UserFederatedIdentity{}.Fields()
	_ = userfederatedidentityFields
	// userfederatedidentityDescProvider is the schema descriptor for provider field.
	userfederatedidentityDescProvider := userfederatedidentityFields[2].Descriptor()
	// userfederatedidentity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	userfederatedidentity.ProviderValidator = func() func(string) error {
		validators := userfederatedidentityDescProvider.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider string) error {
			for _, fn := range fns {
				if err := fn(provider); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userfederatedidentityDescSubject is the schema descriptor for subject field.
	userfederatedidentityDescSubject := userfederatedidentityFields[3].Descriptor()
	// userfederatedidentity.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	userfederatedidentity.SubjectValidator = func() func(string) error {
		validators := userfederatedidentityDescSubject.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(subject string) error {
			for _, fn := range fns {
				if err := fn(subject); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userfederatedidentityDescEmail is the schema descriptor for email field.
	userfederatedidentityDescEmail := userfederatedidentityFields[4].Descriptor()
	// userfederatedidentity.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	userfederatedidentity.EmailValidator = userfederatedidentityDescEmail.Validators[0].(func(string) error)
	// userfederatedidentityDescEmailVerified is the schema descriptor for email_verified field.
	userfederatedidentityDescEmailVerified := userfederatedidentityFields[5].Descriptor()
	// userfederatedidentity.DefaultEmailVerified holds the default value on creation for the email_verified field.
	userfederatedidentity.DefaultEmailVerified = userfederatedidentityDescEmailVerified.Default.(bool)
	// userfederatedidentityDescDisplayName is the schema descriptor for display_name field.
	userfederatedidentityDescDisplayName := userfederatedidentityFields[6].Descriptor()
	// userfederatedidentity.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	userfederatedidentity.DisplayNameValidator = userfederatedidentityDescDisplayName.Validators[0].(func(string) error)
	// userfederatedidentityDescRawProfileEtag is the schema descriptor for raw_profile_etag field.
	userfederatedidentityDescRawProfileEtag := userfederatedidentityFields[8].Descriptor()
	// userfederatedidentity.RawProfileEtagValidator is a validator for the "raw_profile_etag" field. It is called by the builders before save.
	userfederatedidentity.RawProfileEtagValidator = userfederatedidentityDescRawProfileEtag.Validators[0].(func(string) error)
	// userfederatedidentityDescCreatedAt is the schema descriptor for created_at field.
	userfederatedidentityDescCreatedAt := userfederatedidentityFields[10].Descriptor()
	// userfederatedidentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	userfederatedidentity.DefaultCreatedAt = userfederatedidentityDescCreatedAt.Default.(func() time.Time)
	// userfederatedidentityDescLinkedAt is the schema descriptor for linked_at field.
	userfederatedidentityDescLinkedAt := userfederatedidentityFields[11].Descriptor()
	// userfederatedidentity.DefaultLinkedAt holds the default value on creation for the linked_at field.
	userfederatedidentity.DefaultLinkedAt = userfederatedidentityDescLinkedAt.Default.(func() time.Time)
	// userfederatedidentityDescUpdatedAt is the schema descriptor for updated_at field.
	userfederatedidentityDescUpdatedAt := userfederatedidentityFields[13].Descriptor()
	// userfederatedidentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userfederatedidentity.DefaultUpdatedAt = userfederatedidentityDescUpdatedAt.Default.(func() time.Time)
	// userfederatedidentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userfederatedidentity.UpdateDefaultUpdatedAt = userfederatedidentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userfederatedidentityDescID is the schema descriptor for id field.
	userfederatedidentityDescID := userfederatedidentityFields[0].Descriptor()
	// userfederatedidentity.DefaultID holds the default value on creation for the id field.
	userfederatedidentity.DefaultID = userfederatedidentityDescID.Default.(func() uuid.UUID)
	useridentityFields := schema.UserIdentity{}.Fields()
	_ = useridentityFields
	// useridentityDescProvider is the schema descriptor for provider field.
	useridentityDescProvider := useridentityFields[2].Descriptor()
	// useridentity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	useridentity.ProviderValidator = useridentityDescProvider.Validators[0].(func(string) error)
	// useridentityDescSubject is the schema descriptor for subject field.
	useridentityDescSubject := useridentityFields[3].Descriptor()
	// useridentity.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	useridentity.SubjectValidator = useridentityDescSubject.Validators[0].(func(string) error)
	// useridentityDescCreatedAt is the schema descriptor for created_at field.
	useridentityDescCreatedAt := useridentityFields[4].Descriptor()
	// useridentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	useridentity.DefaultCreatedAt = useridentityDescCreatedAt.Default.(func() time.Time)
	// useridentityDescUpdatedAt is the schema descriptor for updated_at field.
	useridentityDescUpdatedAt := useridentityFields[5].Descriptor()
	// useridentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useridentity.DefaultUpdatedAt = useridentityDescUpdatedAt.Default.(func() time.Time)
	// useridentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useridentity.UpdateDefaultUpdatedAt = useridentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// useridentityDescID is the schema descriptor for id field.
	useridentityDescID := useridentityFields[0].Descriptor()
	// useridentity.DefaultID holds the default value on creation for the id field.
	useridentity.DefaultID = useridentityDescID.Default.(func() uuid.UUID)
	userpasskeyFields := schema.UserPasskey{}.Fields()
	_ = userpasskeyFields
	// userpasskeyDescCredentialID is the schema descriptor for credential_id field.
	userpasskeyDescCredentialID := userpasskeyFields[2].Descriptor()
	// userpasskey.CredentialIDValidator is a validator for the "credential_id" field. It is called by the builders before save.
	userpasskey.CredentialIDValidator = userpasskeyDescCredentialID.Validators[0].(func([]byte) error)
	// userpasskeyDescPublicKey is the schema descriptor for public_key field.
	userpasskeyDescPublicKey := userpasskeyFields[3].Descriptor()
	// userpasskey.PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	userpasskey.PublicKeyValidator = userpasskeyDescPublicKey.Validators[0].(func([]byte) error)
	// userpasskeyDescRpID is the schema descriptor for rp_id field.
	userpasskeyDescRpID := userpasskeyFields[4].Descriptor()
	// userpasskey.RpIDValidator is a validator for the "rp_id" field. It is called by the builders before save.
	userpasskey.RpIDValidator = userpasskeyDescRpID.Validators[0].(func(string) error)
	// userpasskeyDescBackupEligible is the schema descriptor for backup_eligible field.
	userpasskeyDescBackupEligible := userpasskeyFields[6].Descriptor()
	// userpasskey.DefaultBackupEligible holds the default value on creation for the backup_eligible field.
	userpasskey.DefaultBackupEligible = userpasskeyDescBackupEligible.Default.(bool)
	// userpasskeyDescBackupState is the schema descriptor for backup_state field.
	userpasskeyDescBackupState := userpasskeyFields[7].Descriptor()
	// userpasskey.DefaultBackupState holds the default value on creation for the backup_state field.
	userpasskey.DefaultBackupState = userpasskeyDescBackupState.Default.(bool)
	// userpasskeyDescSignCount is the schema descriptor for sign_count field.
	userpasskeyDescSignCount := userpasskeyFields[8].Descriptor()
	// userpasskey.DefaultSignCount holds the default value on creation for the sign_count field.
	userpasskey.DefaultSignCount = userpasskeyDescSignCount.Default.(uint32)
	// userpasskeyDescName is the schema descriptor for name field.
	userpasskeyDescName := userpasskeyFields[11].Descriptor()
	// userpasskey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	userpasskey.NameValidator = userpasskeyDescName.Validators[0].(func(string) error)
	// userpasskeyDescRevoked is the schema descriptor for revoked field.
	userpasskeyDescRevoked := userpasskeyFields[12].Descriptor()
	// userpasskey.DefaultRevoked holds the default value on creation for the revoked field.
	userpasskey.DefaultRevoked = userpasskeyDescRevoked.Default.(bool)
	// userpasskeyDescCreatedAt is the schema descriptor for created_at field.
	userpasskeyDescCreatedAt := userpasskeyFields[14].Descriptor()
	// userpasskey.DefaultCreatedAt holds the default value on creation for the created_at field.
	userpasskey.DefaultCreatedAt = userpasskeyDescCreatedAt.Default.(func() time.Time)
	// userpasskeyDescUpdatedAt is the schema descriptor for updated_at field.
	userpasskeyDescUpdatedAt := userpasskeyFields[15].Descriptor()
	// userpasskey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userpasskey.DefaultUpdatedAt = userpasskeyDescUpdatedAt.Default.(func() time.Time)
	// userpasskey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userpasskey.UpdateDefaultUpdatedAt = userpasskeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userpasskeyDescID is the schema descriptor for id field.
	userpasskeyDescID := userpasskeyFields[0].Descriptor()
	// userpasskey.DefaultID holds the default value on creation for the id field.
	userpasskey.DefaultID = userpasskeyDescID.Default.(func() uuid.UUID)
	userrefFields := schema.UserRef{}.Fields()
	_ = userrefFields
	// userrefDescCreatedAt is the schema descriptor for created_at field.
	userrefDescCreatedAt := userrefFields[2].Descriptor()
	// userref.DefaultCreatedAt holds the default value on creation for the created_at field.
	userref.DefaultCreatedAt = userrefDescCreatedAt.Default.(func() time.Time)
	// userrefDescUpdatedAt is the schema descriptor for updated_at field.
	userrefDescUpdatedAt := userrefFields[3].Descriptor()
	// userref.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userref.DefaultUpdatedAt = userrefDescUpdatedAt.Default.(func() time.Time)
	// userref.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userref.UpdateDefaultUpdatedAt = userrefDescUpdatedAt.UpdateDefault.(func() time.Time)
	usersessionFields := schema.UserSession{}.Fields()
	_ = usersessionFields
	// usersessionDescSelector is the schema descriptor for selector field.
	usersessionDescSelector := usersessionFields[2].Descriptor()
	// usersession.SelectorValidator is a validator for the "selector" field. It is called by the builders before save.
	usersession.SelectorValidator = func() func([]byte) error {
		validators := usersessionDescSelector.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
		}
		return func(selector []byte) error {
			for _, fn := range fns {
				if err := fn(selector); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usersessionDescValidatorHash is the schema descriptor for validator_hash field.
	usersessionDescValidatorHash := usersessionFields[3].Descriptor()
	// usersession.ValidatorHashValidator is a validator for the "validator_hash" field. It is called by the builders before save.
	usersession.ValidatorHashValidator = func() func([]byte) error {
		validators := usersessionDescValidatorHash.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
		}
		return func(validator_hash []byte) error {
			for _, fn := range fns {
				if err := fn(validator_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usersessionDescIPAddress is the schema descriptor for ip_address field.
	usersessionDescIPAddress := usersessionFields[4].Descriptor()
	// usersession.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	usersession.IPAddressValidator = usersessionDescIPAddress.Validators[0].(func(string) error)
	// usersessionDescUserAgent is the schema descriptor for user_agent field.
	usersessionDescUserAgent := usersessionFields[5].Descriptor()
	// usersession.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	usersession.UserAgentValidator = usersessionDescUserAgent.Validators[0].(func(string) error)
	// usersessionDescDeviceName is the schema descriptor for device_name field.
	usersessionDescDeviceName := usersessionFields[6].Descriptor()
	// usersession.DeviceNameValidator is a validator for the "device_name" field. It is called by the builders before save.
	usersession.DeviceNameValidator = usersessionDescDeviceName.Validators[0].(func(string) error)
	// usersessionDescLastActiveAt is the schema descriptor for last_active_at field.
	usersessionDescLastActiveAt := usersessionFields[7].Descriptor()
	// usersession.DefaultLastActiveAt holds the default value on creation for the last_active_at field.
	usersession.DefaultLastActiveAt = usersessionDescLastActiveAt.Default.(func() time.Time)
	// usersessionDescCreatedAt is the schema descriptor for created_at field.
	usersessionDescCreatedAt := usersessionFields[8].Descriptor()
	// usersession.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersession.DefaultCreatedAt = usersessionDescCreatedAt.Default.(func() time.Time)
	// usersessionDescUpdatedAt is the schema descriptor for updated_at field.
	usersessionDescUpdatedAt := usersessionFields[9].Descriptor()
	// usersession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usersession.DefaultUpdatedAt = usersessionDescUpdatedAt.Default.(func() time.Time)
	// usersession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usersession.UpdateDefaultUpdatedAt = usersessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// usersessionDescExpiresAt is the schema descriptor for expires_at field.
	usersessionDescExpiresAt := usersessionFields[10].Descriptor()
	// usersession.DefaultExpiresAt holds the default value on creation for the expires_at field.
	usersession.DefaultExpiresAt = usersessionDescExpiresAt.Default.(func() time.Time)
	// usersessionDescAbsoluteExpiry is the schema descriptor for absolute_expiry field.
	usersessionDescAbsoluteExpiry := usersessionFields[11].Descriptor()
	// usersession.DefaultAbsoluteExpiry holds the default value on creation for the absolute_expiry field.
	usersession.DefaultAbsoluteExpiry = usersessionDescAbsoluteExpiry.Default.(func() time.Time)
	// usersessionDescID is the schema descriptor for id field.
	usersessionDescID := usersessionFields[0].Descriptor()
	// usersession.DefaultID holds the default value on creation for the id field.
	usersession.DefaultID = usersessionDescID.Default.(func() uuid.UUID)
}
