// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"sanzi.io/muid/internal/authn/ent/oidcrefreshtoken"
	"sanzi.io/muid/internal/authn/ent/predicate"
	"sanzi.io/muid/internal/authn/ent/userpasskey"
	"sanzi.io/muid/internal/authn/ent/userref"
	"sanzi.io/muid/internal/authn/ent/usersession"
)

// UserRefQuery is the builder for querying UserRef entities.
type UserRefQuery struct {
	config
	ctx                   *QueryContext
	order                 []userref.OrderOption
	inters                []Interceptor
	predicates            []predicate.UserRef
	withSessions          *UserSessionQuery
	withPasskeys          *UserPasskeyQuery
	withOidcRefreshTokens *OIDCRefreshTokenQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserRefQuery builder.
func (_q *UserRefQuery) Where(ps ...predicate.UserRef) *UserRefQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UserRefQuery) Limit(limit int) *UserRefQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UserRefQuery) Offset(offset int) *UserRefQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UserRefQuery) Unique(unique bool) *UserRefQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UserRefQuery) Order(o ...userref.OrderOption) *UserRefQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySessions chains the current query on the "sessions" edge.
func (_q *UserRefQuery) QuerySessions() *UserSessionQuery {
	query := (&UserSessionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userref.Table, userref.FieldID, selector),
			sqlgraph.To(usersession.Table, usersession.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userref.SessionsTable, userref.SessionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPasskeys chains the current query on the "passkeys" edge.
func (_q *UserRefQuery) QueryPasskeys() *UserPasskeyQuery {
	query := (&UserPasskeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userref.Table, userref.FieldID, selector),
			sqlgraph.To(userpasskey.Table, userpasskey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userref.PasskeysTable, userref.PasskeysColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOidcRefreshTokens chains the current query on the "oidc_refresh_tokens" edge.
func (_q *UserRefQuery) QueryOidcRefreshTokens() *OIDCRefreshTokenQuery {
	query := (&OIDCRefreshTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userref.Table, userref.FieldID, selector),
			sqlgraph.To(oidcrefreshtoken.Table, oidcrefreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, userref.OidcRefreshTokensTable, userref.OidcRefreshTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserRef entity from the query.
// Returns a *NotFoundError when no UserRef was found.
func (_q *UserRefQuery) First(ctx context.Context) (*UserRef, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userref.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UserRefQuery) FirstX(ctx context.Context) *UserRef {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserRef ID from the query.
// Returns a *NotFoundError when no UserRef ID was found.
func (_q *UserRefQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userref.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UserRefQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserRef entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserRef entity is found.
// Returns a *NotFoundError when no UserRef entities are found.
func (_q *UserRefQuery) Only(ctx context.Context) (*UserRef, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userref.Label}
	default:
		return nil, &NotSingularError{userref.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UserRefQuery) OnlyX(ctx context.Context) *UserRef {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserRef ID in the query.
// Returns a *NotSingularError when more than one UserRef ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UserRefQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userref.Label}
	default:
		err = &NotSingularError{userref.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UserRefQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserRefs.
func (_q *UserRefQuery) All(ctx context.Context) ([]*UserRef, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserRef, *UserRefQuery]()
	return withInterceptors[[]*UserRef](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UserRefQuery) AllX(ctx context.Context) []*UserRef {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserRef IDs.
func (_q *UserRefQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(userref.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UserRefQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UserRefQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UserRefQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UserRefQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UserRefQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UserRefQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserRefQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UserRefQuery) Clone() *UserRefQuery {
	if _q == nil {
		return nil
	}
	return &UserRefQuery{
		config:                _q.config,
		ctx:                   _q.ctx.Clone(),
		order:                 append([]userref.OrderOption{}, _q.order...),
		inters:                append([]Interceptor{}, _q.inters...),
		predicates:            append([]predicate.UserRef{}, _q.predicates...),
		withSessions:          _q.withSessions.Clone(),
		withPasskeys:          _q.withPasskeys.Clone(),
		withOidcRefreshTokens: _q.withOidcRefreshTokens.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSessions tells the query-builder to eager-load the nodes that are connected to
// the "sessions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserRefQuery) WithSessions(opts ...func(*UserSessionQuery)) *UserRefQuery {
	query := (&UserSessionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSessions = query
	return _q
}

// WithPasskeys tells the query-builder to eager-load the nodes that are connected to
// the "passkeys" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserRefQuery) WithPasskeys(opts ...func(*UserPasskeyQuery)) *UserRefQuery {
	query := (&UserPasskeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPasskeys = query
	return _q
}

// WithOidcRefreshTokens tells the query-builder to eager-load the nodes that are connected to
// the "oidc_refresh_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserRefQuery) WithOidcRefreshTokens(opts ...func(*OIDCRefreshTokenQuery)) *UserRefQuery {
	query := (&OIDCRefreshTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOidcRefreshTokens = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserRef.Query().
//		GroupBy(userref.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UserRefQuery) GroupBy(field string, fields ...string) *UserRefGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserRefGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = userref.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.UserRef.Query().
//		Select(userref.FieldUsername).
//		Scan(ctx, &v)
func (_q *UserRefQuery) Select(fields ...string) *UserRefSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UserRefSelect{UserRefQuery: _q}
	sbuild.label = userref.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserRefSelect configured with the given aggregations.
func (_q *UserRefQuery) Aggregate(fns ...AggregateFunc) *UserRefSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UserRefQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !userref.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UserRefQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserRef, error) {
	var (
		nodes       = []*UserRef{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withSessions != nil,
			_q.withPasskeys != nil,
			_q.withOidcRefreshTokens != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserRef).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserRef{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSessions; query != nil {
		if err := _q.loadSessions(ctx, query, nodes,
			func(n *UserRef) { n.Edges.Sessions = []*UserSession{} },
			func(n *UserRef, e *UserSession) { n.Edges.Sessions = append(n.Edges.Sessions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPasskeys; query != nil {
		if err := _q.loadPasskeys(ctx, query, nodes,
			func(n *UserRef) { n.Edges.Passkeys = []*UserPasskey{} },
			func(n *UserRef, e *UserPasskey) { n.Edges.Passkeys = append(n.Edges.Passkeys, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOidcRefreshTokens; query != nil {
		if err := _q.loadOidcRefreshTokens(ctx, query, nodes,
			func(n *UserRef) { n.Edges.OidcRefreshTokens = []*OIDCRefreshToken{} },
			func(n *UserRef, e *OIDCRefreshToken) {
				n.Edges.OidcRefreshTokens = append(n.Edges.OidcRefreshTokens, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UserRefQuery) loadSessions(ctx context.Context, query *UserSessionQuery, nodes []*UserRef, init func(*UserRef), assign func(*UserRef, *UserSession)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*UserRef)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usersession.FieldUserID)
	}
	query.Where(predicate.UserSession(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(userref.SessionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserRefQuery) loadPasskeys(ctx context.Context, query *UserPasskeyQuery, nodes []*UserRef, init func(*UserRef), assign func(*UserRef, *UserPasskey)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*UserRef)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(userpasskey.FieldUserID)
	}
	query.Where(predicate.UserPasskey(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(userref.PasskeysColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserRefQuery) loadOidcRefreshTokens(ctx context.Context, query *OIDCRefreshTokenQuery, nodes []*UserRef, init func(*UserRef), assign func(*UserRef, *OIDCRefreshToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*UserRef)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(oidcrefreshtoken.FieldUserID)
	}
	query.Where(predicate.OIDCRefreshToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(userref.OidcRefreshTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *UserRefQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UserRefQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userref.Table, userref.Columns, sqlgraph.NewFieldSpec(userref.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userref.FieldID)
		for i := range fields {
			if fields[i] != userref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UserRefQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(userref.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = userref.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserRefGroupBy is the group-by builder for UserRef entities.
type UserRefGroupBy struct {
	selector
	build *UserRefQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UserRefGroupBy) Aggregate(fns ...AggregateFunc) *UserRefGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UserRefGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserRefQuery, *UserRefGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UserRefGroupBy) sqlScan(ctx context.Context, root *UserRefQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserRefSelect is the builder for selecting fields of UserRef entities.
type UserRefSelect struct {
	*UserRefQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UserRefSelect) Aggregate(fns ...AggregateFunc) *UserRefSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UserRefSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserRefQuery, *UserRefSelect](ctx, _s.UserRefQuery, _s, _s.inters, v)
}

func (_s *UserRefSelect) sqlScan(ctx context.Context, root *UserRefQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
