// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"sanzi.io/muid/internal/authn/ent/predicate"
	"sanzi.io/muid/internal/authn/ent/useremail"
)

// UserEmailUpdate is the builder for updating UserEmail entities.
type UserEmailUpdate struct {
	config
	hooks    []Hook
	mutation *UserEmailMutation
}

// Where appends a list predicates to the UserEmailUpdate builder.
func (_u *UserEmailUpdate) Where(ps ...predicate.UserEmail) *UserEmailUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *UserEmailUpdate) SetIsPrimary(v bool) *UserEmailUpdate {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *UserEmailUpdate) SetNillableIsPrimary(v *bool) *UserEmailUpdate {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserEmailUpdate) SetUpdatedAt(v time.Time) *UserEmailUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserEmailMutation object of the builder.
func (_u *UserEmailUpdate) Mutation() *UserEmailMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserEmailUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserEmailUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserEmailUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserEmailUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserEmailUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useremail.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserEmailUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserEmail.user"`)
	}
	if _u.mutation.IdentityCleared() && len(_u.mutation.IdentityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserEmail.identity"`)
	}
	return nil
}

func (_u *UserEmailUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useremail.Table, useremail.Columns, sqlgraph.NewFieldSpec(useremail.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(useremail.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useremail.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(useremail.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useremail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserEmailUpdateOne is the builder for updating a single UserEmail entity.
type UserEmailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserEmailMutation
}

// SetIsPrimary sets the "is_primary" field.
func (_u *UserEmailUpdateOne) SetIsPrimary(v bool) *UserEmailUpdateOne {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *UserEmailUpdateOne) SetNillableIsPrimary(v *bool) *UserEmailUpdateOne {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserEmailUpdateOne) SetUpdatedAt(v time.Time) *UserEmailUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserEmailMutation object of the builder.
func (_u *UserEmailUpdateOne) Mutation() *UserEmailMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserEmailUpdate builder.
func (_u *UserEmailUpdateOne) Where(ps ...predicate.UserEmail) *UserEmailUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserEmailUpdateOne) Select(field string, fields ...string) *UserEmailUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserEmail entity.
func (_u *UserEmailUpdateOne) Save(ctx context.Context) (*UserEmail, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserEmailUpdateOne) SaveX(ctx context.Context) *UserEmail {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserEmailUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserEmailUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserEmailUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useremail.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserEmailUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserEmail.user"`)
	}
	if _u.mutation.IdentityCleared() && len(_u.mutation.IdentityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserEmail.identity"`)
	}
	return nil
}

func (_u *UserEmailUpdateOne) sqlSave(ctx context.Context) (_node *UserEmail, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useremail.Table, useremail.Columns, sqlgraph.NewFieldSpec(useremail.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserEmail.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useremail.FieldID)
		for _, f := range fields {
			if !useremail.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useremail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(useremail.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useremail.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(useremail.FieldRevokedAt, field.TypeTime)
	}
	_node = &UserEmail{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useremail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
