// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"sanzi.io/muid/internal/authn/ent/userfederatedidentity"
)

// UserFederatedIdentity is the model entity for the UserFederatedIdentity schema.
type UserFederatedIdentity struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ProviderUserID holds the value of the "provider_user_id" field.
	ProviderUserID string `json:"provider_user_id,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserFederatedIdentity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userfederatedidentity.FieldID:
			values[i] = new(sql.NullInt64)
		case userfederatedidentity.FieldUserID, userfederatedidentity.FieldProvider, userfederatedidentity.FieldProviderUserID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserFederatedIdentity fields.
func (_m *UserFederatedIdentity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userfederatedidentity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userfederatedidentity.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case userfederatedidentity.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case userfederatedidentity.FieldProviderUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_user_id", values[i])
			} else if value.Valid {
				_m.ProviderUserID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserFederatedIdentity.
// This includes values selected through modifiers, order, etc.
func (_m *UserFederatedIdentity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserFederatedIdentity.
// Note that you need to call UserFederatedIdentity.Unwrap() before calling this method if this UserFederatedIdentity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserFederatedIdentity) Update() *UserFederatedIdentityUpdateOne {
	return NewUserFederatedIdentityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserFederatedIdentity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserFederatedIdentity) Unwrap() *UserFederatedIdentity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserFederatedIdentity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserFederatedIdentity) String() string {
	var builder strings.Builder
	builder.WriteString("UserFederatedIdentity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_user_id=")
	builder.WriteString(_m.ProviderUserID)
	builder.WriteByte(')')
	return builder.String()
}

// UserFederatedIdentities is a parsable slice of UserFederatedIdentity.
type UserFederatedIdentities []*UserFederatedIdentity
