// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"sanzi.io/muid/internal/authn/ent/useridentity"
	"sanzi.io/muid/internal/authn/ent/userref"
	"sanzi.io/muid/internal/authn/ent/usersession"
)

// UserRefCreate is the builder for creating a UserRef entity.
type UserRefCreate struct {
	config
	mutation *UserRefMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *UserRefCreate) SetEmail(v string) *UserRefCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetLastLoginAt sets the "last_login_at" field.
func (_c *UserRefCreate) SetLastLoginAt(v time.Time) *UserRefCreate {
	_c.mutation.SetLastLoginAt(v)
	return _c
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_c *UserRefCreate) SetNillableLastLoginAt(v *time.Time) *UserRefCreate {
	if v != nil {
		_c.SetLastLoginAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserRefCreate) SetCreatedAt(v time.Time) *UserRefCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserRefCreate) SetNillableCreatedAt(v *time.Time) *UserRefCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserRefCreate) SetUpdatedAt(v time.Time) *UserRefCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserRefCreate) SetNillableUpdatedAt(v *time.Time) *UserRefCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserRefCreate) SetID(v uuid.UUID) *UserRefCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddSessionIDs adds the "sessions" edge to the UserSession entity by IDs.
func (_c *UserRefCreate) AddSessionIDs(ids ...uuid.UUID) *UserRefCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the UserSession entity.
func (_c *UserRefCreate) AddSessions(v ...*UserSession) *UserRefCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// AddIdentityIDs adds the "identities" edge to the UserIdentity entity by IDs.
func (_c *UserRefCreate) AddIdentityIDs(ids ...uuid.UUID) *UserRefCreate {
	_c.mutation.AddIdentityIDs(ids...)
	return _c
}

// AddIdentities adds the "identities" edges to the UserIdentity entity.
func (_c *UserRefCreate) AddIdentities(v ...*UserIdentity) *UserRefCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIdentityIDs(ids...)
}

// Mutation returns the UserRefMutation object of the builder.
func (_c *UserRefCreate) Mutation() *UserRefMutation {
	return _c.mutation
}

// Save creates the UserRef in the database.
func (_c *UserRefCreate) Save(ctx context.Context) (*UserRef, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserRefCreate) SaveX(ctx context.Context) *UserRef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRefCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRefCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserRefCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userref.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userref.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserRefCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "UserRef.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := userref.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UserRef.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserRef.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserRef.updated_at"`)}
	}
	return nil
}

func (_c *UserRefCreate) sqlSave(ctx context.Context) (*UserRef, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserRefCreate) createSpec() (*UserRef, *sqlgraph.CreateSpec) {
	var (
		_node = &UserRef{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userref.Table, sqlgraph.NewFieldSpec(userref.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(userref.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.LastLoginAt(); ok {
		_spec.SetField(userref.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userref.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userref.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userref.SessionsTable,
			Columns: []string{userref.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userref.IdentitiesTable,
			Columns: []string{userref.IdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserRefCreateBulk is the builder for creating many UserRef entities in bulk.
type UserRefCreateBulk struct {
	config
	err      error
	builders []*UserRefCreate
}

// Save creates the UserRef entities in the database.
func (_c *UserRefCreateBulk) Save(ctx context.Context) ([]*UserRef, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserRef, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserRefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserRefCreateBulk) SaveX(ctx context.Context) []*UserRef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRefCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRefCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
