// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrganizationsColumns holds the columns for the "organizations" table.
	OrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "domain", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OrganizationsTable holds the schema information for the "organizations" table.
	OrganizationsTable = &schema.Table{
		Name:       "organizations",
		Columns:    OrganizationsColumns,
		PrimaryKey: []*schema.Column{OrganizationsColumns[0]},
	}
	// OrganizationMembersColumns holds the columns for the "organization_members" table.
	OrganizationMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
		{Name: "role_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// OrganizationMembersTable holds the schema information for the "organization_members" table.
	OrganizationMembersTable = &schema.Table{
		Name:       "organization_members",
		Columns:    OrganizationMembersColumns,
		PrimaryKey: []*schema.Column{OrganizationMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_members_organizations_members",
				Columns:    []*schema.Column{OrganizationMembersColumns[3]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "organization_members_organization_roles_members",
				Columns:    []*schema.Column{OrganizationMembersColumns[4]},
				RefColumns: []*schema.Column{OrganizationRolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "organization_members_user_refs_organization_memberships",
				Columns:    []*schema.Column{OrganizationMembersColumns[5]},
				RefColumns: []*schema.Column{UserRefsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organizationmember_organization_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{OrganizationMembersColumns[3], OrganizationMembersColumns[5]},
			},
			{
				Name:    "organizationmember_user_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationMembersColumns[5]},
			},
			{
				Name:    "organizationmember_role_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationMembersColumns[4]},
			},
		},
	}
	// OrganizationRolesColumns holds the columns for the "organization_roles" table.
	OrganizationRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 64},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "is_system", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
	}
	// OrganizationRolesTable holds the schema information for the "organization_roles" table.
	OrganizationRolesTable = &schema.Table{
		Name:       "organization_roles",
		Columns:    OrganizationRolesColumns,
		PrimaryKey: []*schema.Column{OrganizationRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_roles_organizations_roles",
				Columns:    []*schema.Column{OrganizationRolesColumns[6]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organizationrole_organization_id_name",
				Unique:  true,
				Columns: []*schema.Column{OrganizationRolesColumns[6], OrganizationRolesColumns[1]},
			},
			{
				Name:    "organizationrole_organization_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationRolesColumns[6]},
			},
		},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "permission", Type: field.TypeString, Size: 128},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "role_id", Type: field.TypeUUID},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_organization_roles_permissions",
				Columns:    []*schema.Column{RolePermissionsColumns[3]},
				RefColumns: []*schema.Column{OrganizationRolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rolepermission_role_id_permission",
				Unique:  true,
				Columns: []*schema.Column{RolePermissionsColumns[3], RolePermissionsColumns[1]},
			},
			{
				Name:    "rolepermission_permission",
				Unique:  false,
				Columns: []*schema.Column{RolePermissionsColumns[1]},
			},
		},
	}
	// UserRefsColumns holds the columns for the "user_refs" table.
	UserRefsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserRefsTable holds the schema information for the "user_refs" table.
	UserRefsTable = &schema.Table{
		Name:       "user_refs",
		Columns:    UserRefsColumns,
		PrimaryKey: []*schema.Column{UserRefsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrganizationsTable,
		OrganizationMembersTable,
		OrganizationRolesTable,
		RolePermissionsTable,
		UserRefsTable,
	}
)

func init() {
	OrganizationMembersTable.ForeignKeys[0].RefTable = OrganizationsTable
	OrganizationMembersTable.ForeignKeys[1].RefTable = OrganizationRolesTable
	OrganizationMembersTable.ForeignKeys[2].RefTable = UserRefsTable
	OrganizationRolesTable.ForeignKeys[0].RefTable = OrganizationsTable
	RolePermissionsTable.ForeignKeys[0].RefTable = OrganizationRolesTable
}
