// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event/v1/mail.proto

package mail

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAddress) Reset() {
	*x = EmailAddress{}
	mi := &file_event_v1_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAddress) ProtoMessage() {}

func (x *EmailAddress) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAddress.ProtoReflect.Descriptor instead.
func (*EmailAddress) Descriptor() ([]byte, []int) {
	return file_event_v1_mail_proto_rawDescGZIP(), []int{0}
}

func (x *EmailAddress) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EmailMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	To            []*EmailAddress        `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Template      string                 `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	Locale        string                 `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`
	Data          map[string]string      `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailMessage) Reset() {
	*x = EmailMessage{}
	mi := &file_event_v1_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailMessage) ProtoMessage() {}

func (x *EmailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailMessage.ProtoReflect.Descriptor instead.
func (*EmailMessage) Descriptor() ([]byte, []int) {
	return file_event_v1_mail_proto_rawDescGZIP(), []int{1}
}

func (x *EmailMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailMessage) GetTo() []*EmailAddress {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EmailMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailMessage) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *EmailMessage) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *EmailMessage) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EmailMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SendOTPEmailEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ProductName   string                 `protobuf:"bytes,6,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOTPEmailEvent) Reset() {
	*x = SendOTPEmailEvent{}
	mi := &file_event_v1_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPEmailEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPEmailEvent) ProtoMessage() {}

func (x *SendOTPEmailEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPEmailEvent.ProtoReflect.Descriptor instead.
func (*SendOTPEmailEvent) Descriptor() ([]byte, []int) {
	return file_event_v1_mail_proto_rawDescGZIP(), []int{2}
}

func (x *SendOTPEmailEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendOTPEmailEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendOTPEmailEvent) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SendOTPEmailEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendOTPEmailEvent) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SendOTPEmailEvent) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SendOTPEmailEvent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SendLoginAlertEmailEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Device        string                 `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLoginAlertEmailEvent) Reset() {
	*x = SendLoginAlertEmailEvent{}
	mi := &file_event_v1_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLoginAlertEmailEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLoginAlertEmailEvent) ProtoMessage() {}

func (x *SendLoginAlertEmailEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLoginAlertEmailEvent.ProtoReflect.Descriptor instead.
func (*SendLoginAlertEmailEvent) Descriptor() ([]byte, []int) {
	return file_event_v1_mail_proto_rawDescGZIP(), []int{3}
}

func (x *SendLoginAlertEmailEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendLoginAlertEmailEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendLoginAlertEmailEvent) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SendLoginAlertEmailEvent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SendLoginAlertEmailEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SendLoginAlertEmailEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *SendLoginAlertEmailEvent) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *SendLoginAlertEmailEvent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_event_v1_mail_proto protoreflect.FileDescriptor

const file_event_v1_mail_proto_rawDesc = "" +
	"\n" +
	"\x13event/v1/mail.proto\x12\x12muid.event.v1.mail\"8\n" +
	"\fEmailAddress\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb6\x02\n" +
	"\fEmailMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x02to\x18\x03 \x03(\v2 .muid.event.v1.mail.EmailAddressR\x02to\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1a\n" +
	"\btemplate\x18\x05 \x01(\tR\btemplate\x12\x16\n" +
	"\x06locale\x18\x06 \x01(\tR\x06locale\x12>\n" +
	"\x04data\x18\a \x03(\v2*.muid.event.v1.mail.EmailMessage.DataEntryR\x04data\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\x11SendOTPEmailEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12!\n" +
	"\fproduct_name\x18\x06 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xeb\x01\n" +
	"\x18SendLoginAlertEmailEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x16\n" +
	"\x06device\x18\x06 \x01(\tR\x06device\x12\x1f\n" +
	"\voccurred_at\x18\a \x01(\x03R\n" +
	"occurredAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAtB\xbb\x01\n" +
	"\x16com.muid.event.v1.mailB\tMailProtoP\x01Z*sanzi.io/muid/api/proto/event/v1/mail;mail\xa2\x02\x04MEVM\xaa\x02\x12Muid.Event.V1.Mail\xca\x02\x12Muid\\Event\\V1\\Mail\xe2\x02\x1eMuid\\Event\\V1\\Mail\\GPBMetadata\xea\x02\x15Muid::Event::V1::Mailb\x06proto3"

var (
	file_event_v1_mail_proto_rawDescOnce sync.Once
	file_event_v1_mail_proto_rawDescData []byte
)

func file_event_v1_mail_proto_rawDescGZIP() []byte {
	file_event_v1_mail_proto_rawDescOnce.Do(func() {
		file_event_v1_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_v1_mail_proto_rawDesc), len(file_event_v1_mail_proto_rawDesc)))
	})
	return file_event_v1_mail_proto_rawDescData
}

var file_event_v1_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_event_v1_mail_proto_goTypes = []any{
	(*EmailAddress)(nil),             // 0: muid.event.v1.mail.EmailAddress
	(*EmailMessage)(nil),             // 1: muid.event.v1.mail.EmailMessage
	(*SendOTPEmailEvent)(nil),        // 2: muid.event.v1.mail.SendOTPEmailEvent
	(*SendLoginAlertEmailEvent)(nil), // 3: muid.event.v1.mail.SendLoginAlertEmailEvent
	nil,                              // 4: muid.event.v1.mail.EmailMessage.DataEntry
}
var file_event_v1_mail_proto_depIdxs = []int32{
	0, // 0: muid.event.v1.mail.EmailMessage.to:type_name -> muid.event.v1.mail.EmailAddress
	4, // 1: muid.event.v1.mail.EmailMessage.data:type_name -> muid.event.v1.mail.EmailMessage.DataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_event_v1_mail_proto_init() }
func file_event_v1_mail_proto_init() {
	if File_event_v1_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_v1_mail_proto_rawDesc), len(file_event_v1_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_v1_mail_proto_goTypes,
		DependencyIndexes: file_event_v1_mail_proto_depIdxs,
		MessageInfos:      file_event_v1_mail_proto_msgTypes,
	}.Build()
	File_event_v1_mail_proto = out.File
	file_event_v1_mail_proto_goTypes = nil
	file_event_v1_mail_proto_depIdxs = nil
}
